### ISSUE TITLE
CKEditor embed code widget does not work

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#105]
Reported by @larowlan on drupal.org (https://www.drupal.org/node/2663008):

Embed a video using the 'embed' tab of media browser
Doesn't work
Edit node again and use the 'library' tab of media browser to select previous video
Works.
First time data-entity-id was undefined.

When this is fixed, the EmbedCode widget should have Jasmine unit tests to prevent the regression.

**Comment by phenaproxima** [comment]
Neither @balsama or myself can reproduce the issue. I have, however, added a passing test of this functionality to the embed_test branch, which should be merged into 8.x-1.x today.

**Comment by balsama** [comment]
Added a functional test of this [here](https://github.com/acquia/lightning/commit/ea934ae76b0d2de8aa09338d5e1874d3cbb5b894) that is passing. We can reopen if we can reproduce this somehow.
