### ISSUE TITLE
Contextual Links for Editing Landing Pages

### ISSUE THREAD

**Issue by damontgomery** [acquia/lightning#115]
Feature Request

Drupal: 8.0.5
Lightning: 8.x-1.x-beta4

As a content editor, given I have placed a block on a landing page, I would like a way to edit this block's content without going to the custom blocks screen.

![demo_landing_page___site-install](https://cloud.githubusercontent.com/assets/397902/13620904/f365833a-e558-11e5-9f30-e17592f6a013.jpg)

I created a landing page. Used the IPE (there is no body on the landing page content type) and placed a block with an embedded image. So far very excellent. I've gone through all the IPE options I can find and there is no way to get an easy link to edit the placed blocks. The contextual links I get are to edit the landing page which doesn't do much since there's nothing in it.

Creating new content is awesome, but there is no easy way to edit existing content.

Feel free to close if I'm missing something.

**Comment by balsama** [comment]
Yeah - this isn't clear right now and lightning needs to have an opinion about this.

One major issue with this right now is that we need to support revisions with our Panelized Nodes/Panels/IPE implementation. So before we provide an easy way to edit blocks in a panelized layout, we need a way to ensure that the user understands what they are editing (which, right now, might include the live revision even though the edit screen was accessed through a future revision).

We do have a related ticket here: https://www.drupal.org/node/2678838

But I think this is a valid feature request independent of that issue. Happy to track it here, but you might get some more attention if you open this on D.O too.

**Comment by mortenson** [comment]
If you use the newest dev release of Panels, this should be fixed and Quickedit/Contextual should function normally (assuming there's no crazy Javascript on your site).

See: https://www.drupal.org/node/2664002
https://www.drupal.org/node/2658270
https://www.drupal.org/node/2666578

**Comment by balsama** [comment]
@mortenson++

We can see about patching Panels (and core?) for our next release. Thanks!

**Comment by balsama** [comment]
This has been committed and will be in our RC1 release which is targeted for Monday, 4 April 2016.
https://www.drupal.org/node/2692391
