### ISSUE TITLE
[Feature Request] Add Http Response Headers/Seckit module in profile

### ISSUE THREAD

**Issue by naveenvalecha** [acquia/lightning#121]
Add Http Response Headers module in profile for securing the headers.

There's a module for that https://github.com/chapter-three/http_response_headers

Blog : https://www.chapterthree.com/how-to-secure-drupal-http-headers

**Comment by phenaproxima** [comment]
I am +1 for this as long as Lightning (or the module itself) provides sane default configuration out of the box so that novices can basically forget it's there, yet rest assured that they have a secure configuration. @balsama?

**Comment by balsama** [comment]
How does this relate to the module by the same name on D.O? (https://github.com/chapter-three/http_response_headers)

Some things that would need to happen before we put this in Lightning
* A compelling argument that describes the need for this and how the module addresses it
* A release on D.O

**Comment by naveenvalecha** [comment]
> How does this relate to the module by the same name on D.O? (https://github.com/chapter-three/http_response_headers)

Yup we should contribute back to the existing module https://www.drupal.org/project/http_response_headers and prefer collaboration and add additional features.
Filed an issue to discuss about it https://github.com/chapter-three/http_response_headers/issues/1

> 
A compelling argument that describes the need for this and how the module addresses it.

From Blog post and from securityheaders.io
This module allows the following HTTP header configurations:
-     X-Xss-Protection : This response header can be used to configure a user-agent's built in reflective XSS protection. Currently, only Microsoft's Internet Explorer, Google Chrome and Safari (WebKit) support this header.
-     X-Frame-Options : Clickjacking protection. Valid values include DENY meaning your site can't be framed, SAMEORIGIN which allows you to frame your own site or ALLOW-FROM https://example.com/ which lets you specify sites that are permitted to frame your own site.
-     X-Content-Type-Options : This header parameter prevents Google Chrome and Internet Explorer from trying to mime-sniff the content-type of a response away from the one being declared by the server. It reduces exposure to drive-by downloads and the risks of user uploaded content that, with clever naming, could be treated as a different content-type, like an executable.


More here https://www.chapterthree.com/blog/how-to-secure-drupal-http-headers

**Comment by naveenvalecha** [comment]
Update : The code on the github has been pushed on the d.o.  https://www.drupal.org/project/http_response_headers 
I have filed a couple of issues yesterday to get a beta release out so that we can include it in here. Here's the plan issue https://www.drupal.org/node/2761943
I'll work on these issues in coming weekends and will post the update here.

**Comment by vijaycs85** [comment]
Thanks @naveenvalecha for raising those issues & sub-tasks. Currently, the Drupal 8 version is just config applicable for all pages globally(which might work for security headers). However Drupal 7 module allows to create rule per node_type/path/user_role (very similar to block configuration in D7 core) as ctools plugin. The D7 equivalent would be D8 plugin, which also address @phenaproxima concern https://github.com/acquia/lightning/issues/121#issuecomment-227142304 of providing default value on profile.

**Comment by CashWilliams** [comment]
Can we compare the features to https://www.drupal.org/project/seckit? Seckit has been the standard recommendation for security headers (in D7) and it looks like it already has a D8 alpha release.

**Comment by naveenvalecha** [comment]
@CashWilliams sure Added seckit module to todo list. Will post the differences soon.

**Comment by badjava** [comment]
There is a beta release in the works for seckit. You can see the updated d8 porting tracker for [more info](https://www.drupal.org/node/2606748).

**Comment by balsama** [comment]
Now that Lightning is better defined, this is more clearly out if it's scope. (We have very few opinions, but those that we do have are strong) SecKit isn't one of them. BLT pulls this in and it could be added to a sub-profile. But it doesn't belong in Lightning itself.
