### ISSUE TITLE
Text Editor and embed buttons page doesn't work

### ISSUE THREAD

**Issue by albertski** [acquia/lightning#128]
After upgrading from rc5 to rc7 the Text Editor and embed buttons page gives the following PHP Error:

Drupal\Component\Plugin\Exception\PluginNotFoundException: The "media_library" plugin does not exist. in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 52 of /var/www/xmd8/docroot/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).

**Comment by balsama** [comment]
Outdated? @albertski Are there steps to reproduce this still? Or can we close as outdated?

**Comment by albertski** [comment]
I am still seeing this issue in 8.x-1.02 on the site that was created with rc5.

Navigate to: Configuration -> Text editor and embed buttons(/admin/config/content/embed)

I get a white screen error "The website encountered an unexpected error. Please try again later." Same error as above in error log.

On a site that was creates with 8.x-1.01 I don't see this issue.  Any idea how to fix on the site that was created from release candidates?  I know things were changing a lot there.

**Comment by phenaproxima** [comment]
Given the error message you posted, my knee-jerk reaction is that this is a botched automatic update (quite possibly Lightning's own fault). Lightning used to provide a "media_library" embed type plugin, but as of the switch to Entity Browser we stopped needing it, and it was removed.

It's a shot in the dark, but try this Drush command:

$ drush cget embed.button.media_browser type_id

If it echoes "media_library", run this:

$ drush cset -y embed.button.media_browser type_id entity

Let me know what happens!

**Comment by albertski** [comment]
I ran the command but it gave back "entity":

`drush cget embed.button.media_browser type_id`
`'embed.button.media_browser:type_id': entity`

I still tried the cset but the issue remains:
`drush cset -y embed.button.media_browser type_id entity`
`Do you want to update type_id key in embed.button.media_browser config? (y/n): y`
`drush cr`
`Cache rebuild complete.`

**Comment by phenaproxima** [comment]
Hmmm. "entity" is what Lightning comes with anyway.

Flailing around further, I wonder if it's a CKEditor misconfiguration. Do ```drush cget editor.editor.rich_text``` and look in the big array of toolbar items. Do you see "media_library" in there anywhere?

**Comment by albertski** [comment]
When I grep "media_library" in my config directory:

grep -r "media_library" ./
.//core.entity_form_display.node.blog.default.yml:        view_mode: media_library
.//core.entity_form_display.node.client.default.yml:        view_mode: media_library
.//core.entity_form_display.node.page.default.yml:        view_mode: media_library
.//core.entity_form_display.node.project.default.yml:        view_mode: media_library
.//core.entity_form_display.paragraph.pa_im.default.yml:        view_mode: media_library
.//core.entity_view_display.media.image.media_library.yml:    - core.entity_view_mode.media.media_library
.//core.entity_view_display.media.image.media_library.yml:id: media.image.media_library
.//core.entity_view_display.media.image.media_library.yml:mode: media_library
.//core.entity_view_display.media.instagram.media_library.yml:    - core.entity_view_mode.media.media_library
.//core.entity_view_display.media.instagram.media_library.yml:id: media.instagram.media_library
.//core.entity_view_display.media.instagram.media_library.yml:mode: media_library
.//core.entity_view_display.media.tweet.media_library.yml:    - core.entity_view_mode.media.media_library
.//core.entity_view_display.media.tweet.media_library.yml:id: media.tweet.media_library
.//core.entity_view_display.media.tweet.media_library.yml:mode: media_library
.//core.entity_view_display.media.video.media_library.yml:    - core.entity_view_mode.media.media_library
.//core.entity_view_display.media.video.media_library.yml:id: media.video.media_library
.//core.entity_view_display.media.video.media_library.yml:mode: media_library
.//core.entity_view_mode.media.media_library.yml:id: media.media_library
.//editor.editor.full_html.yml:            - media_library
.//embed.button.media_library.yml:id: media_library
.//embed.button.media_library.yml:type_id: media_library

**Comment by albertski** [comment]
Don't see media library when  running `drush cget editor.editor.rich_text`:

drush cget editor.editor.rich_text
uuid: 7fd4a01d-71e9-4ab1-9340-3a8f0180d462
langcode: en
status: true
dependencies:
  config:
    - filter.format.rich_text
  module:
    - ckeditor
_core:
  default_config_hash: rbQ0I2Z6QK2NYhoSktIdnpA34pU5Sc-3P8NHAM-466I
format: rich_text
editor: ckeditor
settings:
  toolbar:
    rows:
      -
        -
          name: Formatting
          items:
            - Bold
            - Italic
            - Strike
            - Superscript
            - Subscript
            - '-'
            - RemoveFormat
        -
          name: Linking
          items:
            - DrupalLink
            - DrupalUnlink
        -
          name: Lists
          items:
            - BulletedList
            - NumberedList
        -
          name: Media
          items:
            - Blockquote
            - media_browser
            - Table
            - HorizontalRule
        -
          name: 'Block Formatting'
          items:
            - Format
        -
          name: Tools
          items:
            - ShowBlocks
            - Source
  plugins:
    language:
      language_list: un
    stylescombo:
      styles: ''
image_upload:
  status: true
  scheme: public
  directory: inline-images
  max_size: ''
  max_dimensions:
    width: null
    height: null

**Comment by phenaproxima** [comment]
What's the output of ```drush cli | grep embed.button.```?

**Comment by albertski** [comment]
embed.button.file_browser
embed.button.media_browser
embed.button.media_entity_embed
embed.button.media_library

**Comment by phenaproxima** [comment]
Try doing the same ```drush cget``` command I mentioned earlier, for each of those embed buttons. The smart money says that at least one of them will still be mentioning media_library...

**Comment by albertski** [comment]
The only one that gives me "media_library" is the media_library button:

`drush cget embed.button.media_library type_id`
`'embed.button.media_library:type_id': media_library`

**Comment by phenaproxima** [comment]
Do the ```drush cset``` magic on it and I suspect you will no longer get the fatal.

**Comment by albertski** [comment]
I get the following:
`drush cset -y embed.button.media_library:type_id entity`
`No config value specified`

**Comment by phenaproxima** [comment]
You don't use the colon :) The correct command is:

```drush cset -y embed.button.media_library type_id entity```

**Comment by albertski** [comment]
That worked.  Thanks for helping with this!
