### ISSUE TITLE
DB update issue with lightning_layout

### ISSUE THREAD

**Issue by jayesbe** [acquia/lightning#133]
I'm fairly new to Drupal.. However I am at an issue where at the moment I really don't know how to continue without serious debugging.

I am attempting to run DB updates. I have also tried running from console with `drush updb`
The following is the output I am getting through the admin interface. 

> lightning_layout module
> 
> Update #8004
> 
> Failed: Drupal\Core\Entity\EntityStorageException: 'entity_view_display' entity with ID 'node.landing_page.full' already exists. in Drupal\Core\Entity\EntityStorageBase->doPreSave() (line 425 of /vagrant/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php).

Can anyone suggest how to continue ?

**Comment by jayesbe** [comment]
Just to add.. 

running Drupal 8.1

here is my current composer.json

> 		"composer/installers" : "^1.0",
> 		"drupal-composer/drupal-scaffold" : "2.0.x-dev",
> 		"cweagans/composer-patches" : "^1.0",
> 		"drupal/lightning" : "8.1.x-dev",
> 		"drupal/accessibility" : "8.1.x-dev",
> 		"drupal/cors" : "dev-master",
> 		"drupal/amp" : "^8.1@beta",
> 		"drupal/restui" : "^8.1",
> 		"drupal/devel" : "8.1.x-dev",
> 		"drupal/migrate_plus" : "8.x-2.x-dev",
> 		"drupal/field_group" : "8.x-1.x-dev",
> 		"drupal/backup_migrate" : "8.x-4.x-dev",
> 		"drupal/simplesamlphp_auth" : "8.x-3.x-dev",
> 		"drupal/s3fs" : "8.x-2.x-dev",
> 		"drupal/cdn" : "8.x-3.x-dev",
> 		"backupmigrate/core" : "dev-master",
> 		"drupal/services" : "8.4.x-dev",
> 		"drupal/jdrupal" : "^8.1",
> 		"symfony/var-dumper" : "^3.1"

**Comment by phenaproxima** [comment]
Damn. That's a good catch, and a legitimate bug in the upgrade path. Try this -- go to line 67 of lightning_layout.install and change that entire "paragraph" from this:

```php
  $values = _lightning_layout_get_view_display('node.landing_page.full');
  try {
    EntityViewDisplay::create($values)->save();
  }
  catch (PreExistingConfigException $e) {
    _lightning_layout_update_panelizer_default_displays('node.landing_page.full');
  }
```

to this:

```php
try {
    _lightning_layout_update_panelizer_default_displays('node.landing_page.full');
}
catch (EntityStorageException $e) {
  $values = _lightning_layout_get_view_display('node.landing_page.full');
  EntityViewDisplay::create($values)->save();
}
```

If that works, let me know and I'll commit the fix into Lightning.

**Comment by jayesbe** [comment]
@phenaproxima Can you say when this will be committed?

**Comment by phenaproxima** [comment]
Hopefully we will commit today. Here is a patch with the fix, so others can use it if they need to.
[lightning-8.x-1.x-133.patch.txt](https://github.com/acquia/lightning/files/335157/lightning-8.x-1.x-133.patch.txt)

**Comment by jayesbe** [comment]
@phenaproxima  Thanks!

**Comment by phenaproxima** [comment]
This is now committed. Sorry for the delay -- it was a busy week!
