### ISSUE TITLE
views_infinite_scroll patch not applying issue.

### ISSUE THREAD

**Issue by naveenvalecha** [acquia/lightning#137]
- Applying patches for drupal/views_infinite_scroll
    https://www.drupal.org/files/issues/no-wrapper-empty-rows-2701881-2.patch (2701881 - View "No results" area doesn't appear even view has no results)
   Could not apply patch! Skipping.

Reason :
There's already a 8.x-1.2 version of the module is out So update to 8.x-1.2
https://www.drupal.org/project/views_infinite_scroll/releases/8.x-1.2

**Comment by naveenvalecha** [comment]
Here's the PR #138 138

**Comment by naveenvalecha** [comment]
PR merged.

**Comment by grasmash** [comment]
https://github.com/acquia/lightning/pull/139
