### ISSUE TITLE
Decoupled from Lightning Distribution?

### ISSUE THREAD

**Issue by EWB** [acquia/lightning#144]
I am wondering if the Lightning Media feature will work with a non-Lightning version of Drupal 8x? 

Thanks

**Comment by GroovyCarrot** [comment]
It will do, but the quirk is that you need to tell Drupal in your `settings.php` file that you installed it using the lightning profile; otherwise it will not see the modules inside.
```
$settings['install_profile'] = 'lightning';
```

It would be nice if the features were separate dependencies however.

**Comment by balsama** [comment]
@EWB - not officially. But as @GroovyCarrot hints, there are definitely ways. I would recommend using the distro and just turning off the features you don't need though. You can use the [Extender](http://lightning.acquia.com/blog/extending-ootb-experiences-lightning) to automatically disable the functional areas of Lightning that you don't use. That will guarantee that the updates work and that you're getting the correct patches to core and other modules.

If you choose to use a Lightning module outside of the distro, the only issue that I know of that will almost definitely cause problems is [Cleaning up config in lightning features and profile](https://www.drupal.org/node/2773519). I'm happy to commit that once the stuff phenaproxima points out is fixed.

**Comment by sylus** [comment]
Apologies for reopening this, feel free to close if inappropriate.

I still think having the media specific (upload, proxy, etc) functionality that is in lightning_media would be best served as a contrib module. Would it not be possible to have most of the abstracted media specific logic under the src directory in its own module? I'd even offer to help maintain the contrib module if there was interest.

I have a use case where we have our own distro with specific requirements. However I really like how the media functionality is handled in lightning. Right now I am forced to port + attrib the specific functionality I want form lightning_media. I would much prefer just extending from a contrib module that we can all share from.

Again feel free to close this issue again just thought I would give it one last attempt. Also thanks for the great resource that is lightning, it has greatly helped me :)
