### ISSUE TITLE
Unable to install Media Image (unmet dependencies)

### ISSUE THREAD

**Issue by seanr** [acquia/lightning#146]
Unable to install Media Image, core.entity_form_display.media.image.media_browser, core.entity_view_display.media.image.embedded, field.field.media.image.field_media_in_library, field.field.media.image.image have unmet dependencies.

Of course it doesn't bother to tell me WHAT freaking dependency.

**Comment by seanr** [comment]
A ksm on the $missing variable in Drupal's validateDependencies method reveals this:

core.entity_form_mode.media.media_browser
core.entity_view_mode.media.embedded
field.storage.media.field_media_in_library
field.storage.media.image

Apparently, lightning_media didn't like being installed via a config sync.  I had to uninstall and reinstall it to get this working.  On examination of the logs, I found this:

Call to a member function set() on a non-object in /.../modules/contrib/lightning_media/lightning_media.install on line 123

**Comment by balsama** [comment]
Please provide steps to reproduce.

**Comment by balsama** [comment]
Also, here's a hand patch/issue to make that unmet dependency exception a little more helpful :)

https://www.drupal.org/node/2655104
