### ISSUE TITLE
[Feature Request] Add Waterwheel to Lightning JS scenario

### ISSUE THREAD

**Issue by mattgrill** [acquia/lightning#148]
# Problem/Motivation

1. **Developer experience:** We want to offer a rich developer experience and appeal to JavaScript developers. Additionally offer a way for people to interact with these components without having to know how to put together React/Angular/Ember components.
2. **Editorial experience:** Editors need to be able to interact with any page component in Drupal even if it is JavaScript-driven, and editors should not need to rely on the developer of these JavaScript components in order to interpolate them into their Drupal pages.

# Solution

We can achieve this by adding [WaterwheelJS](https://www.drupal.org/project/waterwheel) and the [Decoupled Blocks Module](https://www.drupal.org/project/pdb) to the Lightning Project. WaterwheelJS will enable JavaScript developers to build application components in their framework of choice which can be interpolated into Drupal using a rich JavaScript API. Decoupled Blocks will help improve the editorial experience by allowing editors to assemble Drupal pages consisting of JavaScript-driven components.

**Comment by balsama** [comment]
Migrated to https://www.drupal.org/node/2797779
