### ISSUE TITLE
Support automatic creation of image fields on node types

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#151]
It's an incredibly common use case for a site builder to require at least one image field attached to a content type, if not two (normal image and teaser image). I propose that Lightning provide some sort of UI to expedite this -- maybe a checkbox on the form to create a new node type: "Add image field" or similar. Maybe even two checkboxes, one for a normal image and one for teaser image, with the option of reusing existing fields.

If the site author opted in to creating an image field (or two), they would NOT be asked to configure the field(s) at that time -- the fields would just be created with sane defaults so as to keep the site builder moving quickly.

**Comment by balsama** [comment]
I was going to migrate this, but I think we can close it since our policy of not messing with the data model has been solidified since then. If it's still something you want to pursue we can reopen in the D.O queue.
