### ISSUE TITLE
Can't change workflow state of a workspace that's in a locked state

### ISSUE THREAD

**Issue by balsama** [acquia/lightning#160]
Once a workspace has been moved into a WBM state that is maked as Locked, it cannot be moved out of that state. Because Lightning is preventing changes to entities on workspaces that are locked?

**Comment by phenaproxima** [comment]
Lightning is preventing changes to entities _in_ locked workspaces, yes...although, during replication, that restriction is lifted. And although a workspace may be in a "locked" state, Lightning is never supposed to prevent changes to the workspace entity itself.
