### ISSUE TITLE
Ensure changes are not pulled when a conflict occurs

### ISSUE THREAD

**Issue by balsama** [acquia/lightning#162]
https://www.drupal.org/node/2791789#comment-11707335

Steps to reproduce:

1. Enable Deploy module
2. Create a node on Live
3. Deploy to Stage
4. Edit the node on Live
5. Edit the node on Stage
6. Deploy from Live to Stage

**Comment by josephdpurcell** [comment]
This issue was expected. See https://www.drupal.org/node/2791789#comment-11709921 and https://www.drupal.org/node/2815883. After the latest patch to Workspace, Deploy should no longer experience this issue described.

**Comment by josephdpurcell** [comment]
Here's an example patch for Deploy https://www.drupal.org/node/2815883#comment-11710081

**Comment by phenaproxima** [comment]
Not a release blocker because Lightning is not to include Deploy (at least, not in this release).

**Comment by phenaproxima** [comment]
Looking at the code, I don't think this is something we'll need to solve in Lightning unless we bring Deploy into it. Closing.
