### ISSUE TITLE
PHP Warning on Workspaces List page

### ISSUE THREAD

**Issue by balsama** [acquia/lightning#167]
Fresh install
1. navigate to `/admin/structure/workspace`
2. PHP Warning:
   
   http://localhost/~adam.balsam/lightning/build/docroot/admin/structure/workspace

**Comment by phenaproxima** [comment]
This is a known issue, now mentioned in our README file (as of commit 7937f2980148c8f8466792ec0463fe0ddaa28604), and not a release blocker. We'll continue to debug this.
