### ISSUE TITLE
Author of node entities is not replicated

### ISSUE THREAD

**Issue by balsama** [acquia/lightning#173]
STR:

* Create node A as Admin on Live
* Update Stage

The author of Node A on stage is Anon

**Comment by balsama** [comment]
Furthermore:

* Create node on Live as user X
* Pull to Stage
* Create new revision on Stage
* Publish Stage
* Author of node on Live is now anon

**Comment by phenaproxima** [comment]
I think this will need input from dixon_, timmillwood, and josephdpurcell. I'm not sure why the author reference is not replicated -- could it be because users live outside any particular workspace? -- but this is a severe problem and major usability fail.

**Comment by phenaproxima** [comment]
I traced this to a simple syntactical bug in Replication: https://www.drupal.org/node/2820105. The 8.x-replication-fix branch brings that patch into Lightning.
