### ISSUE TITLE
Unable to embed image using 'Media Browser' embed button.

### ISSUE THREAD

**Issue by msherron** [acquia/lightning#181]
When trying to embed an already uploaded image using the 'Library' tab in the Media Browser embed button, we receive an error, 'No display options available for the selected entity. Please select another entity.' We receive this error no matter what image we select.

Lightning: 8.1.11
Core: 8.2.1

![image](https://cloud.githubusercontent.com/assets/1399395/19457744/92cb16e2-947c-11e6-95ac-df934cc84f22.png)

As a workaround, if I go to admin/config/content/embed/button/manage/media_browser, and fill in the 'Image' checkbox under 'Media bundle', and select an 'Allowed Entity Embed Display plugins' (Embedded and Thumbnail make sense), then the library picker works as expected.

It seems like the default should be that all plugins work for all Media bundles, but that doesn't seem to be the case.

**Comment by balsama** [comment]
I don't think this bug report is still reproducible. Please reopen if it is.
