### ISSUE TITLE
Drush failed while applying patch

### ISSUE THREAD

**Issue by naveenvalecha** [acquia/lightning#188]
Steps to Reproduce 
1. Clone the latest code
2. composer clear-cache
3. composer install

you'll see the error during drush install

<img width="1251" alt="screen shot 2016-10-25 at 00 10 11" src="https://cloud.githubusercontent.com/assets/2075378/19658913/75734ef4-9a47-11e6-8587-d3c6325b24ee.png">

**Comment by phenaproxima** [comment]
That almost always means that the code base against which the patch was applied has changed (i.e., the patch needs a re-roll). I haven't personally encountered this one, so I'm closing this issue, but feel free to re-open it if you see it again.
