### ISSUE TITLE
Failed installation with composer on Windows machine

### ISSUE THREAD

**Issue by gmacor** [acquia/lightning#189]
The installation with composer failed. Same error from several attempts. 
Machine: Win 10 pro , XAMPP, php7

![image](https://cloud.githubusercontent.com/assets/23008533/19693701/1f32ea88-9ae5-11e6-8e22-b9cffd190885.png)

On same machine i can install lightning from tarball or other Drupal composer  project ( eg Drupal OpenSocial).

Thank you.

Gabriel

**Comment by phenaproxima** [comment]
I think this might be out of Lightning's scope. Lightning Project uses Composer's ProcessExecutor class to run NPM, and it looks to me like the failure is originating there. Chances are it is something specific to your local machine.

http://stackoverflow.com/questions/30296288/php-warning-proc-open-createprocess-failed-error-code-267

**Comment by gmacor** [comment]
Please compare the followings with your local composer installation.

The folder structure from installation  from tarball can be different ( by design) than the structure from composer install? 

Structure from tarball:
drupal_install/profiles/lightning/modules/lightning_features/ 
drupal_install/profiles/lightning/modules/contrib/ >> here are 30 modules ( acquia_connector, config_update, ctools .. )

Structure from composer:
drupal_install/docroot/profiles/contrib/lightning/modules/lightning_features/ 
drupal_install/docroot/profiles/contrib/lightning/modules/ >> the above modules are not installed

**Comment by phenaproxima** [comment]
The tarball and Composer installers are supposed to generate different trees. That is perfectly fine.

**Comment by gmacor** [comment]
I found the missing files. The question is why the function deployLibraries not work ok.

**Comment by phenaproxima** [comment]
I'm not sure, but I suspect it is a problem with your local machine, because Lightning defers to Composer's process execution functionality to run NPM (which is all that deployLibraries does, really). Can you reproduce it under any other circumstances? I do not have access to a Windows machine so unfortunately I cannot verify the problem.

**Comment by gmacor** [comment]
On same machine, Lightning was installed ok using composer on XAMPP with php 5.6.
Right now i can't reproduce in other circumstances.

**Comment by phenaproxima** [comment]
In that case, I really don't think this is a Lightning issue. It sounds like some sort of bug arising from the combination of Composer (specifically its ProcessExecutor class), Windows, and PHP 7. I would recommend filing an issue in composer/composer.
