### ISSUE TITLE
View modes should support help text

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#195]
This is inspired by #194.

If we implement that, I think we should also implement the concept of view mode
descriptions. I think it would be helpful to authors if site builders could attach help
text to a view mode, explaining how the view mode is used and where, and perhaps what it
looks like, or anything else pertinent or peculiar. We could then display that help text
as the description of each select list presented by the Panelizer widget, as a way of
helping authors choose which layout they'd like to use. 

Additionally, any help text attached to a view mode should be displayed when editing that
view mode, via hook_help().

**Comment by koleary** [comment]
That's a really good idea.
