### ISSUE TITLE
Add notifications to state transitions

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#196]
This is an oft-requested feature and a very valid one. People should be able to configure notifications when moderated content changes states.

I'm not sure exactly how we'll go about implementing this in the most Lightning-ey way possible, but I would like to use Rules if we can. It has an alpha2 release just over a month old, so active development is clearly proceeding. The use of Rules will also enable us to ultimately migrate a some Lightning functionality to Rules, which would only increase its flexibility and overridability.

**Comment by phenaproxima** [comment]
Today @klausi confirmed on IRC that Rules is not ready for prime time, so if we do this soon, it will have to be using some other system. I'm loath to roll our own code for this, since it'll likely be hard to maintain and test...any ideas?

**Comment by balsama** [comment]
Possible puzzle piece: https://www.drupal.org/project/message

Does it make sense to tackle this before the CM migration?

**Comment by phenaproxima** [comment]
CM adoption is still a ways off, and this is something people are *constantly* asking for. I think we should do it now and migrate it to CM, if needed. (It's possible that it will "just work", depending on how it's architected.)

**Comment by balsama** [comment]
Remember, CM adoption is < 5 months away :) But I agree. It shouldn't block us from starting this.

**Comment by phenaproxima** [comment]
OK, so I did a cursory bit of research into this and I'm honestly not sure we can proceed with the current tools at our disposal.

We appear to have three options:

* Message Stack. I took a look at this module and quite frankly it doesn't seem "done" to me. It's not clear to me how it works, how it's used, how it's extended, or even if the API is finalized. It looks like it wants to be the successor to Notifications (which is all but abandoned), but it doesn't seem to be anywhere near Notifications' level of completeness. I'd love to be convinced otherwise, but this is my initial impression of Message Stack.

* Rules. It's not ready for prime time. The API is ready, or so I'm told, but the UI is broken and delaying the module for...well, like a year now. I'd prefer to build this sort of thing on Rules, but not if even Rules' maintainers are telling us it's not ready to go.

* Rolling our own. By far the worst option, IMHO -- notifications are a personal thing, and they need to be *extremely* flexible. Building this ourselves would entail time and technical investments we can't afford.

Personally, I think we should throw whatever resources at either Rules (preferred) or Message Stack.

**Comment by sylus** [comment]
Can't speak to D8 version of Message Stack as haven't had a chance to investigate it yet; but I can say it has provided a great toolset in D7 and was used extensively by our Open Data initiative.

I'd love to hear @amitaibu take on this before going done the Rules route as customized notifications seems to me at least to be Message stacks wheelhouse.

**Comment by amitaibu** [comment]
Hi folks. The message stack for D8 is live and kicking, so you can go ahead an use it. As for Rules, I'm not sure what the state is, but I _personally_ prefer using hooks/ event subscribers.

**Comment by balsama** [comment]
Migrated to https://www.drupal.org/project/lightning/issues/2924496
