### ISSUE TITLE
Roles should support descriptive text

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#214]
Similar to #195, except applicable to user roles instead of view modes. Roles are a great candidate for supporting arbitrary descriptions because they are also heavily site-specific and potentially confusing about what permissions they grant. We could easily add descriptive text to user roles, then display that text as the description of each role-granting checkbox when creating or editing a user account.

@koleary, what say you?

**Comment by koleary** [comment]
Great idea. +1

**Comment by phenaproxima** [comment]
Issue migrated to drupal.org: https://www.drupal.org/node/2825926

**Comment by phenaproxima** [comment]
Merged!
