### ISSUE TITLE
Integrate Lightning testing with Acquia Cloud

### ISSUE THREAD

**Issue by grasmash** [acquia/lightning#229]
Pre-requisites: 
* https://github.com/acquia/lightning/issues/230

Requirements:

* Once Lightning is using Pipelines, use "on_success" trigger to 
    1. Deploy pipelines artifact to an Acquia environment
    2. Install Lightning

Blockers:
* MS-1874

**Comment by balsama** [comment]
Completed with 9d2db880d865f2156488728dcee821642cc9a1eb and 07a8376770795e3217e057d925d14e9149e74818. See DPL-752 and and DPL-692.
