### ISSUE TITLE
Integrate Lightning testing with Pipelines

### ISSUE THREAD

**Issue by grasmash** [acquia/lightning#230]
Prerequisites:
* https://github.com/acquia/lightning/pull/215

Requirements:
* Add acquia-pipelines.yml to Lightning repository.
* Connect Pipelines to Lightning GitHub repo.

**Comment by balsama** [comment]
see #282

**Comment by balsama** [comment]
committed in: 9d2db880d865f2156488728dcee821642cc9a1eb
