### ISSUE TITLE
New Site installs in Acquia Cloud Site Factory fail to use lightning.extend.yml if file is placed in sites/default.

### ISSUE THREAD

**Issue by msherron** [acquia/lightning#231]
.. but the extend file will work fine if it's placed in sites/all. We should update the documentation to reflect that.

**Comment by balsama** [comment]
I think we had an issue on D.O where it was explained that this is works as designed. Whether we could add further documentation remains undecided, but either way, the extender is being removed in the next release of lightning in favor of sub-profiles. See https://www.drupal.org/node/2855793#comment-11972290
