### ISSUE TITLE
Can drush be downgraded to the stable 8.x branch?

### ISSUE THREAD

**Issue by ba66e77** [acquia/lightning#233]
The current composer.json requires `"drush/drush": "^9.0"`.  The closest to a stable release of the 9.x version of drush is [9.0.0-alpha1, released in March](https://github.com/drush-ops/drush/releases/tag/9.0.0-alpha1).  In the meantime, the 8.x branch has resolved several issues, including a problem with `config-import --partial` which prevents installation of module schemas: https://github.com/drush-ops/drush/issues/2069#issuecomment-233325717

Is the unstable 9.x branch of drush really required or could it be viably downgraded to 8.x?

**Comment by ba66e77** [comment]
For historical perspective, it looks like Lightning was first set up to use drush's dev-master branch in March (commit https://github.com/acquia/lightning/commit/cb3f4c6) then updated in May to use ^9.0 (commit https://github.com/acquia/lightning/commit/3028a13d).

On cursory inspection, it appears that the changes which were brought in by switching to 9.0-alpha1 are currently also in the 8.x-1.x branch.

**Comment by balsama** [comment]
> Can drush be downgraded to the stable 8.x branch?

yes :)

I think the original patch to make-convert which we used only applied to 9.x at the time, but that's no longer the case.
