### ISSUE TITLE
Security update for Media module returns an error

### ISSUE THREAD

**Issue by shaysmith** [acquia/lightning#256]
There is a security update available for the media module. Updating this module by itself does not appear to be an option because the following error is returned and the site displays a blank page (sitename removed from paths):

`[21-Dec-2016 17:24:58 America/New_York] PHP Fatal error:  require_once(): Failed opening required '/mnt/www/html/<sitename>/docroot/profiles/lightning/modules/contrib/media/modules/media_wysiwyg/includes/media_wysiwyg.features.inc' (include_path='.:/var/www/html/<sitename>/library/:/usr/share/php:/usr/share/pear') in /mnt/www/html/<sitename>/docroot/profiles/lightning/modules/contrib/media/modules/media_wysiwyg/media_wysiwyg.module on line 18 request_id="v-4e8915b4-c7cc-11e6-be2c-22000ab21ee3"`

**Comment by balsama** [comment]
Which module specifically? It looks like you might be trying to use the Drupal 7 Media module with Lightning - which is definitely not supported :)

**Comment by shaysmith** [comment]
Has the security fix from vanilla media module been incorporated into the Lightning version of the module?

**Comment by balsama** [comment]
Lightning doesn't use the media module. There is no supported version of the media module for Drupal 8. Lightning uses media entity... and there are currently no security update for any modules that Lightning uses: https://www.drupal.org/project/lightning/releases/8.x-2.01
