### ISSUE TITLE
Error installing 2.0.2 with composer

### ISSUE THREAD

**Issue by leonk** [acquia/lightning#258]
If I try and update to 2.0.2 I get the following error messages from composer:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: drupal/workbench_moderation[1.2.0, 1.1.0].
    - Can only install one of: drupal/workbench_moderation[1.1.0, 1.2.0].
    - Can only install one of: drupal/workbench_moderation[1.2.0, 1.1.0].
    - acquia/lightning 2.0.2 requires drupal/workbench_moderation 1.2.0 -> satisfiable by drupal/workbench_moderation[1.2.0].
    - Installation request for acquia/lightning ~2.0.2 -> satisfiable by acquia/lightning[2.0.2].
    - Installation request for drupal/workbench_moderation (locked at 1.1.0) -> satisfiable by drupal/workbench_moderation[1.1.0].
```

Looks like you still have 1.1.0 in the composer.lock file.  So I'm guessing this needs to be updated? 

Side question: could you not remove the composer.lock file from your repo? (As this is how normal packages work).  
That way if I wanted to update drupal/core I wouldn't have to wait for you to update your composer.lock file first.

**Comment by balsama** [comment]
We commit the lock file to our Lightning repo so that all people contributing are working with the same dependencies. This is fairly standard. That lock file is ignored if you're using a scaffold project, such as [Lightning Project](https://github.com/acquia/lightning-project), that requires Lightning. Lightning Project does _not_ commit its lock file.

**Comment by leonk** [comment]
Yes I used the scaffold project to get setup initially.  But this does not prevent the lock file from being downloaded.  The scaffold project points to this project (https://github.com/acquia/lightning-project/blob/8.2.x/composer.json#L25) so it will download the lock file from there.

**Comment by balsama** [comment]
Ok cool. I can say with a high level of confidence that the lock file that comes with Lightning is ignored in that case (with lightning as a dependency).

Can you try requiring lightning 2.0.2 and updating dependencies as separate commands? I.e.:

    $ composer require acquia/lightning:2.0.2 --no-update
    $ composer update

I would think that just running `composer update` should work for you given that you don't have lightning pinned to a release, but I would try the above just to be sure.

**Comment by leonk** [comment]
Why would it be ignored?  

Try running:
```composer create-project acquia/lightning-project MY_PROJECT```
It will download the lock file into the docroot/profiles/contrib/lightning 

When I run those commands I still get the original error.  The lock file inside this project needs updating (or needs to be removed).

**Comment by phenaproxima** [comment]
It is never downloading the lock file, because there isn't one to download: https://github.com/acquia/lightning-project

The lock file is *generated* anew by composer create-project during the install stage. You can test this yourself:

```
composer create-project acquia/lightning-project MY_PROJECT --no-install
cd MY_PROJECT
ls composer.lock
```

**Comment by leonk** [comment]
Yes I won't have my own project lock file, but I will still have the Acquia lightning lock file.  

```
composer create-project acquia/lightning-project MY_PROJECT
ll MY_PROJECT/docroot/profiles/contrib/lightning/composer.lock
```
It's this lock file that is causing the issue above, not my project level one.

I think it's fairly standard practise _not_ to include a lock file in packages that are intended as components.  See this: https://philsturgeon.uk/php/2014/11/04/composer-its-almost-always-about-the-lock-file/#summary

**Comment by leonk** [comment]
Ah okay got it running by doing a `composer update` 
Which I was trying to avoid, as I didn't want to update all my packages, the old version of that module must have been in my project's composer.lock, and not in the lightning one.

**Comment by balsama** [comment]
Oh good. FWIW, you can do

    $ composer update acquia/lightning --with-dependencies

Which won't touch stuff not directly related to lightning.

**Comment by leonk** [comment]
Ah great, thanks for your help @balsama 

So does composer not read the lock files of subpackages?  Because if not then yes it's fine to have a lock file in this project.  If it does then wouldn't there potentially be issues at some point?   Say another composer package requires the same library as lightning, but not the exact same version as in the lock file.

**Comment by balsama** [comment]
[It does not](https://getcomposer.org/doc/02-libraries.md#lock-file):

> For your library you may commit the composer.lock file if you want to. This can help your team to always test against the same dependency versions. **However, this lock file will not have any effect on other projects that depend on it**. It only has an effect on the main project.

Funny enough, we had an issue last summer that saw the fact that it was ignored as a problem:
[composer.lock files are not used in child dependencies](https://www.drupal.org/node/2745949)
