### ISSUE TITLE
build doesn't include themes folder in docroot, which in turn makes phpunit fatal

### ISSUE THREAD

**Issue by matthewmorley** [acquia/lightning#260]
`[13-Jan-2017 09:56:56 America/New_York] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/Users/my.user/Sites/A/docroot/web/themes): failed to open dir: No such file or directory' in /Users/my.user/Sites/A/docroot/web/core/tests/bootstrap.php:23`

**Comment by phenaproxima** [comment]
I addressed this in commit 7a6920d627e1adc8fd923e69d8f48822bcfadbe2, which creates those directories when running the Phing install target. Will that suffice? If not, I can probably add them to the composer.json's post-install-cmd script.
