### ISSUE TITLE
Panelized pages cannot be translated

### ISSUE THREAD

**Issue by danepowell** [acquia/lightning#263]
In my testing, it appears that Panelizer (or at least IPE) doesn't play nicely with content translation. Specifically, blocks placed via Panelizer are not isolated to the translation they are created with, so any changes to blocks affect all translations of that page.

Testing steps:

1. Start with vanilla Lightning 2.0.1
2. Install Language and Content Translation modules.
3. Add a new language (e.g. German) and configure Landing pages to be translatable (all fields).
4. Create a new landing page in English. Use IPE to add a basic block to the page with English content.
5. Add a German translation of the page. Use IPE to edit the existing block to be in German.
6. Return to the English version of the page.

Expected behavior:
English version of page contains English block

Actual behavior:
English version of page contains German block

**Comment by phenaproxima** [comment]
Pinging @EclipseGc, @mortenson and @japerry.

**Comment by phenaproxima** [comment]
@EclipseGc, do you think that inline blocks will solve this?

**Comment by mortenson** [comment]
We use IPE, Panelizer, Custom Blocks, and translation without major issues. That said, when we work on Custom Block translations, we always use the backend editor (i.e. /block/N/edit), or Quick Edit, not IPE. It's possible that there's a bug with IPE where the Custom Block edit route does not properly load the correct translation.

**Comment by balsama** [comment]
Just confirming that I can reproduce the problem described. Outside of a fix in Panels (or a hack in Lightning), we'll have to confirm and see if we can document the workaround.

**Comment by phenaproxima** [comment]
@danepowell, I believe that what you described is, at the moment, expected. Even though it sucks.

I think that inline blocks will fix this, once they land in the Panels ecosystem. Implementing them involves changes to CTools, Panels, Panelizer, and IPE:

https://www.drupal.org/node/2842170
https://www.drupal.org/node/2844054

If we were going to implement a workaround, I think one possible approach would be:

1) Ensure full translation is enabled for all custom block types.
2) When a panelized node (i.e., a landing page) is translated, create equivalent translations for all the custom blocks it refers to. I don't think this happens currently.
3) Ensure that IPE is loading and saving the block translation.

The thing is, when you create a custom block in IPE right now, it creates an actual custom block with its own existence apart from the landing page. As far as I know, it does not get translated along with the landing page; the landing page just refers to it, and that's that. Inline blocks would encode the block as a blob in the landing page's panelizer field, so any translation work done on it would be preserved with the landing page.

Does that make sense? I don't do translation work very much so I may be far off the mark here -- @mortenson or @EclipseGc, will you confirm that I'm not talking completely out of my butt?

**Comment by mortenson** [comment]
@phenaproxima Yep, you're on the right track.

Most of IPEs operations are based on a Panels Storage ID and Tempstore ID, so if Panelizer provided unique IDs per language, I would expect IPE operations to "just work". IPE isn't really aware that it's being used on a storage type that supports multilingual, so this work would need to happen in Panelizer.

For Custom Blocks, IPE could be updated to explicitly load the right translation when editing/creating things, which wouldn't be super easy but is something that IPE is solely responsible for. You're correct in thinking that inline blocks would work, as long as the Panelizer storage ID was language-specific.

**Comment by danepowell** [comment]
I'm reviewing old issues in preparation for the d.o issue migration. Does anyone know if this is still a valid issue? I honestly haven't used Panelizer in months, I know a lot has changed.

**Comment by balsama** [comment]
I believe it is still valid. Migrated to https://www.drupal.org/project/lightning/issues/2924493
