### ISSUE TITLE
Overriding configuration provided by Lightning

### ISSUE THREAD

**Issue by danepowell** [acquia/lightning#265]
Right now there are two main methods of configuration management (CM) for installed sites. One is to use the core CM system--placing config into /config/default and importing it on deploys. The other is to use Features--packaging the config into individual modules and importing Features individually or in bulk (features-revert-all) on deploys. For various reasons, Features is currently the only practical option for certain sites (the core CM system isn't very versatile and doesn't support multisite well, etc...)

CM with Lightning-based installs is a challenge. One problem is that Lightning provides all of its config as Features, and Features by default does not allow the same configuration to be exported twice (even in uninstalled modules). This means that in order to maintain an override to Lightning-provided configuration right now, you either have to use the core config system (untenable for some sites) or force Features to allow conflicts. Allowing conflicts isn't ideal, as it opens the door for silly mistakes later on (new developers exporting the same config yet again in a different feature), and I've heard reports that it doesn't behave as expected (conflicting config doesn't actually get imported).

The easiest solution would be to remove the *.features.yml files from Lightning, i.e. allow the configuration to be provided as normal Drupal modules rather than as Features. I don't think this would have any negative side effects, since Lightning already provides config updates via update hooks--it doesn't assume you're going to import (revert) features. And indeed it shouldn't... the paradigm in D8 seems to be that once a module provides a default configuration, that configuration is "owned" by the site and no longer by the module.

**Comment by balsama** [comment]
Migrated to D.O: https://www.drupal.org/node/2846724

**Comment by balsama** [comment]
9890eff704e923e00176a63b7e319514f2daffa4
