### ISSUE TITLE
Access denied: /admin/config/system/lightning

### ISSUE THREAD

**Issue by leonk** [acquia/lightning#295]
I'm logged in with user 1, and I get an access denied for Lightning Core settings page.

**Comment by balsama** [comment]
Can't reproduce this. What version are you on and is this an updated or a fresh install?

**Comment by leonk** [comment]
I've tested against a clean install of Lightning 8.x-2.05 (which I can confirm there is no issue).

On the site I have where it's an issue, two things are different
a) user 1 does not have the administrator role
b) the administrator role does not have is_admin set to true.

I think because it was initially installed with no lightning modules enabled (including lightning_core) is why it ended up that way.

But now that lightning_core is a dependency on the installation profile (since https://github.com/acquia/lightning/commit/4fe4537621dd050544ef610abf50d47dfc1ff8eb) this is no longer an issue and can be closed.
