### ISSUE TITLE
PHP Fatal Error when installing lightning_media

### ISSUE THREAD

**Issue by leonk** [acquia/lightning#297]
I'm trying to install lightning_media onto an existing Lightning install.  I've installed it on the module on local instance, and then exported the config (via `drush cex`) to my git repo.  Whenever I try and re-import the config onto my staging db I get the following error:

`PHP Fatal error:  Call to a member function set() on null in /var/www/uniper/docroot/profiles/contrib/lightning/modules/lightning_features/lightning_media/lightning_media.install on line 134`

Looks like the lightning_media install is trying to load the media_browser embed button:
`EmbedButton::load('media_browser')`
However this is not created yet, so it's erroring.

I do have the yml file for this piece of configuration in my site config.  And it's listed as being a item that should be created as part of the config-import.  But it looks like Drupal is trying to install the lightning_media module first, before importing the config.
So I'm not really sure what I can do about this one.  Apart from installing lightning_media manually, and then re-exporting the config (so basically doing two separate deployments).

**Comment by LightGuard** [comment]
I'm seeing the same thing here on 2.1.0 (I believe the line numbers have changed though)

**Comment by balsama** [comment]
We added bail-outs during config sync to fix the problem of config already being exported/imported in your scenario (see: https://github.com/acquia/lightning/blob/8.x-2.x/modules/lightning_features/lightning_media/lightning_media.install#L20). That should have fixed this issue as well. Let us know if you can still reproduce though. Thanks!

**Comment by LightGuard** [comment]
I didn't see any issues installing 2.1.3 on an existing site.
