### ISSUE TITLE
SubProfile with custom extends.yml  + Lightning

### ISSUE THREAD

**Issue by sylus** [acquia/lightning#304]
Hi there! ^_^

I implemented a sub-profile of lightning before the inherited base profile patch + generator got added (though using the patch myself). One question I had is I wanted others profiles to be able to extend off of my install profiles and not lightning trusting its default configuration. As a result we re-used the logic for how lightning handles the install_profile.extend.yml file in our own custom profile. Essentially duplicating the logic in `src/Extender.php` but for our install profiles custom extend.yml file. As an example:

Open Data (Calls WxT profile but provides its own extend)

https://github.com/open-data/od (install profile)
https://github.com/drupalwxt/site-wxt (composer-project)

WxT (Calls Lightning profile but provides its own extend) 

https://github.com/drupalwxt/wxt (install profile)
https://github.com/drupalwxt/site-wxt (composer-project)

Is there any issue you might notice with doing it this way? I noticed the logic changed in the src folder between 2.03 and 2.05 so I wonder if there might be a better way ^_^

P.S. I really appreciate the amazing work that is being done in this profile, so wanted to just say thank you once again :)

**Comment by sylus** [comment]
Hazaa!

https://docs.acquia.com/lightning/subprofile#diff was exactly what i needed, sorry didn't catch that earlier. Thanks again!

**Comment by balsama** [comment]
Oh good. Glad you answered your question and sorry I didn't get back to you sooner. Looks like you're doing some pretty big projects on Lightning. Let me know if you'd like to get an invite to our bi-weekly update meetings.

**Comment by sylus** [comment]
@balsama we are indeed using lightning as a base for quite a few projects.

I would love to get an invite to your bi-weekly update meetings.

Email is sylus1984@gmail.com

Thanks again!
