### ISSUE TITLE
Publishing a node translation unpublishes other translations

### ISSUE THREAD

**Issue by danepowell** [acquia/lightning#306]
On our project we are using Content Translation, Interface Translation, and Workbench 8.x-1.1. The symptom we see is that whenever a translation is published, it unpublishes any other translation drafts.

We were able to reproduce this bug using the following steps:

- Create a node and translate it into multiple languages
- Edit more than 1 of the translations (leave them as draft)
- Both will still appear as "published" in the /node/*/translations screen
- Now edit one of those translations (doesn't matter which) and set the status back to published and save
- Go back to /node/*/translations, note that the other language that was edited will now display as "draft" state and will no longer be anonymously accessible

This might share a root cause with this [drupal.org issue](https://www.drupal.org/node/2768615#comment-11974576).

**Comment by balsama** [comment]
Agree that this is the same problem reported in #2768615 and #2766957.

The ultimate solution will hopefully be in #2766957, but that relies on Content Moderation, which is still experimental. As a workaround until Content Moderation is marked as stable and Lightning migrates to it, you can use the [Content Translation Workflow](https://www.drupal.org/project/content_translation_workflow) module.

1. Apply [this core patch](https://www.drupal.org/files/issues/2809227-140.patch) (already committed to 8.3.x).
1. Add the [Content Translation Moderation module](https://www.drupal.org/project/content_translation_workflow) to your codebase and enable it.

There are some caveats. See [Forward Revisions and Translated Content](http://lightning.acquia.com/blog/forward-revisions-and-translated-content) on our blog for more information.

**Comment by balsama** [comment]
Workaround is documented. This is ultimately fixed in Content Moderation by not allowing multiple forward translations - which Lightning will eventually migrate to.
