### ISSUE TITLE
Move "Moderation state" and "Scheduled update" field widgets to secondary pane in Seven theme

### ISSUE THREAD

**Issue by TravisCarden** [acquia/lightning#310]
The "Seven" admin theme moves lots of meta data fields to the secondary region (on the right side) of the node edit form in `seven_form_node_form_alter()`. Can we move "Moderation state" and "Scheduled update" fields over there, too? I don't mind doing it myself on my projects, but it seems like a sensible default to me, so I thought I'd propose it here.

**Comment by balsama** [comment]
Good idea. Probably not something we'll get to til 2.1.1, but it makes sense to do it. Thanks.

**Comment by phenaproxima** [comment]
I'm in favor, if you submit a PR (a test would be beneficial as well).

**Comment by balsama** [comment]
Migrated to https://www.drupal.org/project/lightning/issues/2924490
