### ISSUE TITLE
Update hook to resolve nodes not appearing in content admin view

### ISSUE THREAD

**Issue by danepowell** [acquia/lightning#328]
As part of [this commit](http://cgit.drupalcode.org/lightning/commit/?id=0d91715), the admin content view was altered so that the relationship to the latest revision is no longer required, resolving an issue with missing content.

However, that only altered the install hook that initially creates the view. It did not provide an update hook as part of lightning_workflow to fix any existing Lightning installations. It _did_ provide an update hook as part of lightning_dev though. But I wouldn't expect most sites to run this hook.

It seems like lightning_workflow should have an update hook to fix that view, let me know if you agree and I can open a PR.

**Comment by balsama** [comment]
Hi Dane.

We could attempt to automatically make that change, but messing with config that the site owner controls is dicey at best.

For stuff like this, we always include manual update steps. See the last bullet in the 2.0.3 -> 2.0.4 manual update instructions here: https://github.com/acquia/lightning/blob/8.x-2.x/UPDATE.md#203-to-204

**Comment by danepowell** [comment]
Ah, I figured there was a method to the madness :smile: I had never seen that document before! I had no idea manual intervention was necessary with updates.

This is probably something that would be good to detail on (or at least link to from) the Drupal.org release notes, which people are probably much more used to reading: https://www.drupal.org/project/lightning/releases/8.x-2.04

On a tangential note... splitting attention between Github and Drupal.org has caused a lot of difficulty like this for me recently. It makes it hard to find issues, release notes, etc... I know it's a tough situation but it would be really nice if one place could become the system of record.

**Comment by balsama** [comment]
> This is probably something that would be good to detail on (or at least link to from) the Drupal.org release notes

Definitely agree. We will do that going forward.

Drupal.org is the issue queue of record. Our README says as much, but we could probably promote that and make it a little more clear. The UPDATE.md file actually lives in the repo - which I think is pretty standard. But definitely a good idea to include the contents in D.O's release notes. Thanks.
