### ISSUE TITLE
Can't update lightning due to search_api composer req/incompatibility

### ISSUE THREAD

**Issue by msherron** [acquia/lightning#329]
Updating Lightning from 2.0.3 > 2.1.0 fails on my current project during composer update/installs with the following error:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for acquia/lightning 2.1.0 -> satisfiable by acquia/lightning[2.1.0].
>     - acquia/lightning 2.1.0 requires drupal/search_api 1.0.0-beta5 -> satisfiable by drupal/search_api[1.0.0-beta5] but these conflict with your requirements or minimum-stability.

Not all projects enable lightning_search, as most PS projects are going to integrate with Acquia Search, and might not want the latest version of Search API.

**Comment by balsama** [comment]
What's the conflict?

**Comment by msherron** [comment]
Like we discussed in HipChat, we're currently running older versions of Search API. Since we're able to not use Lightning Search at all as a submodule, it stands to reason the core composer file shouldn't be dictating whether Search API is installed, or what version is installed.

**Comment by sylus** [comment]
Yes the hardcoded restriction to 1.0.0-beta5 at least should be removed, as it blocks me from updating search_api to the latest rc1 release.

**Comment by phenaproxima** [comment]
We cannot loosen the constraint until https://www.drupal.org/node/2866454 is committed. However, we can certainly update to RC1.

**Comment by balsama** [comment]
Just to further clarify, we pin to specific releases if any of the following is true:

* The project is in alpha
* **The project requires a patch**
* An compatibility or vulnerability exists in most recent version

As @phenaproxima said, we can update to RC1 in HEAD and we'll roll another release before drupalcon.

**Comment by sylus** [comment]
Thanks for the clarification, I will add that to my notes. Very helpful :)

**Comment by phenaproxima** [comment]
I just committed #334, which loosens the Search API constraint to ^1.0, now that RC2 has been rolled with https://www.drupal.org/node/2866454 committed.
