### ISSUE TITLE
Error in EntityDisplayModeAddForm during upgrade from 2.0.3 to 2.1.0 

### ISSUE THREAD

**Issue by AMDAndy** [acquia/lightning#333]
After updating composer blt local:refresh is giving me the following error:

> PHP Fatal error:  Class 'Drupal\field_ui\Form\EntityDisplayModeAddForm' not found in /var/www/projectname/docroot/profiles/contrib/lightning/modules/lightning_features/lightning_core/src/Form/EntityDisplayModeAddForm.php on line 11
> 
> Fatal error: Class 'Drupal\field_ui\Form\EntityDisplayModeAddForm' not found in /var/www/projectname/docroot/profiles/contrib/lightning/modules/lightning_features/lightning_core/src/Form/EntityDisplayModeAddForm.php on line 11
> Drush command terminated abnormally due to an unrecoverable error.       [error]

Composer update had no errors. I had updated composer.json with the config suggested in https://github.com/acquia/blt/issues/1325#issuecomment-292245617.

**Comment by balsama** [comment]
related #327

**Comment by phenaproxima** [comment]
This was corrected in #340.
