### ISSUE TITLE
Flickr integration for Lightning Media - new module

### ISSUE THREAD

**Issue by dakkusingh** [acquia/lightning#338]
Hi guys, 
I have been working on Lightning integration with Flickr. The module is almost ready... so if anyone is willing to try the module and provide a peer review / feedback testing, I could do with some collaboration.

Module on D.O
https://www.drupal.org/project/lightning_media_flickr

For collaboration, feedback and PRs please use github..
https://github.com/dakkusingh/lightning_media_flickr

Cross posting here for visibility to Lightning users.

**Comment by phenaproxima** [comment]
Looks great! Thanks for this!

@balsama, maybe we should mention this (plus any others that appear over time) in our README, and in our composer.json as suggestions.

**Comment by dakkusingh** [comment]
@phenaproxima @balsama - I made additions to README.md to add additional integration modules.
https://github.com/acquia/lightning/pull/339

**Comment by phenaproxima** [comment]
#339 is merged :) Thanks for your contributions, @dakkusingh.
