### ISSUE TITLE
Cannot manage configuration provided by Lightning Media

### ISSUE THREAD

**Issue by danepowell** [acquia/lightning#343]
Currently, you cannot manage the configuration provided by Lightning Media, and in fact you can't really use the module at all if you want to use the core configuration system.

The cause is described in this core issue: https://www.drupal.org/node/2870864

In a nutshell: a standard configuration management workflow would be to export your entire site's configuration (including default config provided by Lightning Media at install time) to a directory in your VCS, such as /config/default. The problem is that you can't subsequently import this configuration without error, as described in the core issue.

This is pretty clearly a core bug, not a bug with Lightning, but I want to raise it here since it will primarily impact Lightning users and potentially impact adoption.

**Comment by danepowell** [comment]
Should be solved by #345

**Comment by balsama** [comment]
Fixed in 587f5c0373da6170f20d88ed718666c61f41d863.
