### ISSUE TITLE
IPE on Panelizer nodes should only allow for custom overrides

### ISSUE THREAD

**Issue by dalibor-matura** [acquia/lightning#347]
There's a patch for Panelizer `8.x-4.x-dev` and `8.x-3.x-dev` to remove "Save as default" option from IPE to make sure it will not wipe out existing layouts. More info on the issue here: https://www.drupal.org/node/2856471

I can see that the most up to date Lightning `composer.json` contains `"drupal/panelizer": "3.0.0-beta1"` and the patch is not there.

**Are you planning to update to `8.x-3.x-dev` or to use the patch or do you have another suggestion?** We solved the problem for now just by CSS hiding it, as we do not want to interfere with Lightning dependencies.

**Comment by phenaproxima** [comment]
This is done in Panelizer 4.x, which we are expecting to merge into LIghtning today (see PR #344).

**Comment by dalibor-matura** [comment]
Thanks for the info Adam, appreciated :)
