### ISSUE TITLE
UI Improvement - Shall we change the star icon to something more "Media" focused?

### ISSUE THREAD

**Issue by dakkusingh** [acquia/lightning#349]
https://github.com/acquia/lightning/blob/8.x-2.x/modules/lightning_features/lightning_media/images/star.png

I am no UI expert, but I think it might be a good idea to replace the star with something that represents clearly that this icon is for embedding media. A user who is not familiar with Lightning might mistake it for "Favourite" or "Bookmark" icon.

Thoughts?

**Comment by phenaproxima** [comment]
I'm open to that, but so far we have not found an icon that can better describe "general purpose media". We can't re-use the image icon, because a) we can't have two image icons, and b) our media functionality is a lot more generalized.

So I'm totally open to suggestions for better icons, if you have any! :)

**Comment by dakkusingh** [comment]
I was thinking something more like this:
https://i2.wp.com/itnews.blog.fordham.edu/wp-content/uploads/2017/01/multimedia-icon.jpg

Obviously we need something that would look good at 32x32 pixel size and 16x16 pixel size.

**Comment by dakkusingh** [comment]
or perhaps something like this:
https://d30y9cdsu7xlg0.cloudfront.net/png/44674-200.png

Afterall, it is Lightning Media Browser

**Comment by phenaproxima** [comment]
I think I like the first suggestion better, because it is much clearer exactly what it does. The second one is a "cleaner" design, but IMHO it doesn't communicate anything beyond "Hey, this does some sort of Lightning-ey thing." I doubt it will be intuitive for users.

**Comment by dakkusingh** [comment]
@phenaproxima I agree, let me try a few mockups in Adobe Illustrator and see what I can come up with :)

**Comment by balsama** [comment]
We talked to our UX team about this and they actually thought that the star had become somewhat of a thing of its own - and like it. I'm closing this for now, but am still open to suggestions. Thanks!
