### ISSUE TITLE
YieldToArgumentTrait prevents the Bundle filter from ever being shown.

### ISSUE THREAD

**Issue by mortenson** [acquia/lightning#351]
Reviewing the logic at [YieldToArgumentTrait.php](https://github.com/acquia/lightning/blob/8.x-2.x/modules/lightning_features/lightning_core/src/YieldToArgumentTrait.php), it looks like there is no case where the "bundle" exposed filter will ever be shown for the Media browser.

If a contextual filter is configured for the view but a fallback value is used, the exposed filter should be shown. This is not the current behavior, which you can see by visiting /admin/structure/views/view/media/edit/entity_browser_1 and seeing that there is no exposed filter present in the View preview, as the contextual filter has a default value of "all".

**Comment by balsama** [comment]
Fixed in e1a733bafb3afc46726452b234fe53fac095ba25. Thanks Sam!
