### ISSUE TITLE
lightning missing from file system

### ISSUE THREAD

**Issue by albertski** [acquia/lightning#353]
I am getting a strange warning.  When I am local (using the same database as pantheon), I run `drush updb -y` and I don't get any warnings.  If I run `drush @pantheon-alias updb -y` I get the following warning:

```
The following module is missing from the file system: lightning        [warning]
bootstrap.inc:240
No database updates required                                           [success]
```

In my core.extension.ytml I do have `lightning: 1000` under modules. If I try to remove that and run `drush cim -y` I get the following error:

`
The import failed due for the following reasons:                     [error]
Unable to uninstall the <em class="placeholder">Lightning</em>
profile since it is an installed profile.
`

I believe `lightning_core` module may have been called `lightning` back in the day (We used Lightning since Release candidates).

**Comment by albertski** [comment]
I think may have been a fluke.  I was on a multi-dev environment and seen this but when I went to dev I didn't see the warning.

**Comment by albertski** [comment]
Actually updated another site and I do see this error on production as well.  On the second site I don't have a `lightning` module in core.extionsions.yml(I do have lightning_core).

**Comment by balsama** [comment]
Hrm. Tough to help troubleshoot from over here. But, back to your original report, if running a command without an alias produces different results than running the same command with an alias, then the logical conclusion is that the alias is pointing to a different codebase.

Some other notes:
* You should see `lightning: 1000` in your core.extension.yml file - so that's correct.
* That is the correct error message that you should get if you remove it.

**Comment by balsama** [comment]
Closing this for now. Please reopen if this reproducible.

**Comment by albertski** [comment]
Ran into this again. Somehow lightning profile got uninstalled.  I had two problems:

Didn't have:
```
$settings['install_profile'] = 'lightning';
```

When I went to the module page I would get errors.  The patch in this issue fixed the problem by reinstalling the profile if exists: https://www.drupal.org/node/1170362

Don't think this was a Lightning issue but somehow the Profile got disabled.
