### ISSUE TITLE
Lightning features are missing when installing through Composer

### ISSUE THREAD

**Issue by dominiquevienne** [acquia/lightning#369]
Hi, 

I am currently creating an automated install script for Lightning using Vagrant. I use **composer** for package dependencies so Lightning is being installed using this line:
`composer create-project acquia/lightning-project:^8.1.0 /vagrant/projectsources --no-interaction`

The result is a functionnal Drupal 8. However, the **Lightning features** you can find here are **missing**  (https://github.com/acquia/lightning/tree/8.x-2.x/modules/lightning_features) on the filesystem. 
I am also unable to find composer packages that would make the deal. 

Is this a bug or a thing I am doing the wrong way?

Thanks

**Comment by balsama** [comment]
Something is awry. The lightning_features module is definitely included. Note that it will be in /docroot/profiles/contrib/lightning/modules/lightning_features. Can you confirm that you're looking in the correct place? Or just visit /admin/extend and see if you see Lightnings components listed.

**Comment by dominiquevienne** [comment]
Sorry for the delay... Had to make some tests!

You're right... Modules are in profile directory... but... I tried to reinstall a brand new Drupal 8 Lightning project and tried to get the modules in extend menu... with no success

I use a Vagrant image in order to create the Drupal ENV
https://www.dropbox.com/s/u11vq5yjkg25tsu/drupal8-skel-master.zip?dl=0

Please, consider that, in this script, lightning_features module is copied from root. You should remove the line in bootstrap.sh in order to test.

**Comment by balsama** [comment]
Please reopen in our D.O issue queue is this is still a problem.
