### ISSUE TITLE
Mismatched entity and/or field definitions after upgrade from 2.06 (multiversion)

### ISSUE THREAD

**Issue by jeremdow** [acquia/lightning#371]
There doesn't seem to be a valid upgrade / removal path for multiversion when upgrading to Lightning ~2.1.0 from any previous version which depended on the multiversion alphas.

I think I've narrowed the issue down to this change:
https://github.com/acquia/lightning/commit/4432246e9fffca1b7cdfe771c8da9a155dbd0a4e#diff-e6c06bb20ab483c55cbadbf543875c4a

When upgrading with multiversion enabled (so it might be properly removed?), it now applies itself to file entities as well, and reports and fails on the revision schema that doesn't exist.

I could submit a pull request, simply reverting the above to what it was before from:
https://github.com/acquia/lightning/commit/818151b2e14b73d8be191b75ba13d9282eddd739#diff-e6c06bb20ab483c55cbadbf543875c4a

But I'm not sure if this is a real solution, or if any thought has been given to support removing multiversion as part of the automated upgrade process?

**Comment by balsama** [comment]
Hi. We moved Lightning Preview and it's dependencies (e.g. Multiversion) to the experimental branch: 8.x-2.x-experimental. You'll have to use that if you're using Lightning Preview until it becomes stable.
