### ISSUE TITLE
Core patches don't apply to 8.3.3

### ISSUE THREAD

**Issue by jimhart3000** [acquia/lightning#381]
Trying to install lightning via composer breaks with the latest core - 8.3.3 - because the patches for drupal/core no longer cleanly apply. Just starting from scratch with `composer create-project acquia/lightning-project` fails.

**Comment by phenaproxima** [comment]
Yup, we are aware of this. We think there might have been a problem with core itself -- we're not sure, but we suspect that it was mistagged. We're monitoring this and we won't roll a new release on drupal.org until we test it and it's resolved.

**Comment by balsama** [comment]
See https://www.drupal.org/node/2884479 and #drupal-contribute on IRC
