### ISSUE TITLE
Update to Lightning 8.x-2.13 breaks panelized displays

### ISSUE THREAD

**Issue by dalibor-matura** [acquia/lightning#382]
> The database updates finished just fine, but the already existing serialized instances of PanelsDisplayVariant in the database are broken. So accessing panelized displays on a url like this /admin/structure/panelizer/edit/node__article__full__default throws an ServiceNotFoundException.

This is an issue with Panels contrib module that I raised in the Panel's issue queue* https://www.drupal.org/node/2884551

**The problem is that it breaks panelized entities after updating to Lightning 8.x-2.13.**

It is a blocker for us.

**Comment by dalibor-matura** [comment]
The Drupal Core version the site after the Lightning 8.x-2.13 update is finished is 8.3.1

**Comment by balsama** [comment]
That makes me question the versions of other dependencies since that's outdated.

What versions of panels and panelizer do you have? Is layout plugin enabled? What about layout discovery? Is there any message with the exception? Did you clear your cache after the update?

**Comment by balsama** [comment]
Oh, I see. All the details are over in the panels issue. Let's move the discussion there:
https://www.drupal.org/node/2884551

**Comment by dalibor-matura** [comment]
Hi Adam,

to make it clear, I mentioned in the title of the issue and also in its description that the Lightning version we updated to is `8.x-2.13` according to  `lightning.info.yml`. But according to Lightning git tags and commit `Issue #2871477: [META] Lightning 8.x-2.1.3` it is `8.x-2.1.3`. So here is the Lightning we are talking about: https://github.com/acquia/lightning/tree/2.1.3

When you open its `composer.json` file https://github.com/acquia/lightning/blob/2.1.3/composer.json, you can read all the versions that are specified there and as such being used on our site immediately after updating to Lightning 8.x-2.1.3

Quoting from `composer.json`:
> 
>  "require": {
>         ...
>         "drupal/core": "~8.3.1",
>         ...
>         "drupal/panels": "^4.0",
>         "drupal/page_manager": "^4.0",
>         "drupal/panelizer": "^4.0",
>         ...

**That indicates that Lightning 8.x-2.1.3 supports Drupal core from version 8.3.1, panels from version 4.0, page_manager from version 4.0 and panelizer from version 4.0.**

So I do not understand why are you in such a rush. All that information is available to you. **If you have solved the problem of Lightning 8.x-2.1.3 distribution breaking panelized displays immediately after you update to it then please share with us the solution. If not, why are you closing this issue that seems to be properly addressed in this project?**

Best Regards,
Dalibor

P.S. There seems to be a workaround https://www.drupal.org/node/2884551#comment-12120667 that I will test soon ;)
