### ISSUE TITLE
Latest version of behat and drupal/extension cause fatal

### ISSUE THREAD

**Issue by balsama** [acquia/lightning#385]
Updating drupal/drupal-extension to 3.3.0 loosens its constraint on behat/behat which means it will update to 3.3.1. After updating, the `Creating media assets from within the media browser using embed codes` fails with the following:

```
@BeforeScenario # PanelsSubContext::gatherContexts()
Fatal error: Call to undefined method Behat\Behat\Context\Environment\UninitializedContextEnvironment::getContexts()
```

Which apparently comes from DrupalSubContextBase::getContext. What's weird is that I don't see UninitializedContextEnvironment ever containing a getContexts method. So I'm not sure what's up but I wanted to document it.

You can see test failure here: https://travis-ci.org/balsama/lightning/builds/243794888 or on lightning-project which doesn't have a lock file and thus updated already.

**Comment by balsama** [comment]
Related issue: https://github.com/jhedstrom/drupalextension/issues/386

**Comment by phenaproxima** [comment]
I think the solution here is going to be to pin to a specific version of Drupal Extension, before this problem was introduced. Is there any reason for us not to do that?

**Comment by balsama** [comment]
No, that's totally acceptable. We'd need to pin/restrict lightning-project as well.

I'd much rather get to the bottom of it, but we can just pin if it's not immediately apparent how to fix whatever broke in drupal/extension.

**Comment by gabe-connolly** [comment]
I am still getting `Fatal error: Call to undefined method Behat\Behat\Context\Environment\UninitializedContextEnvironment::getContexts()` when trying to use a Behat Scenario Outline:

```
Scenario Outline: Test a page for a 200 response code
    Given I am on "<url>"
    Then the response status code should be <response_code>

    Examples:
      | url    | response_code |
      | homepage | 200         |
```

I have updated to acquia/lightning 2.1.5 and done a `composer update`, but I'm still having no luck getting my behat tests to complete without fatal errors.  Are there any other manual update steps needed to make the getContexts() method available?

**Comment by balsama** [comment]
@gabe-connolly Yeah - these are dev dependencies, so they won't bubble up to your scaffold project.

You should change:

```
"drupal/drupal-extension": "^3.2"
```

to

```
"drupal/drupal-extension": "~3.2.0"
```

In your root composer.json file. And then run composer.update.

**Comment by gabe-connolly** [comment]
Thanks, @balsama .  When I try to run a composer update, I'm getting a drupal package issue:

> [Composer\DependencyResolver\SolverProblemsException]                                                                          
>     Problem 1                                                                                                                    
>       - The requested package drupal/drupal-extension 3.2.0 exists as drupal/drupal-extension[v3.3.0] but these are rejected by your constraint. 

I've spent a while trying to work around this, but with no luck.  I seems like this would affect lightning as well, are you seeing the same issue there?

In case it's helpful, here is my full required block from composer.json:

```
"require": {
        "acquia/blt": "^8.8",
        "acquia/lightning": "^2.1.5",
        "cweagans/composer-patches": "^1.6.0",
        "drupal/acsf": "^1.32.0",
        "drupal/drupal-extension": "~3.2.0",
        "drush/drush": "^8.1.8",
        "drupal/address": "~1.0",
        "drupal/geophp": "1.0.0-beta1",
        "drupal/geofield": "~1.0-alpha2",
        "drupal/geocoder": "2.x-dev",
        "drupal/console-extend": "^0.4.0",
        "drupal/masquerade": "2.x-dev",
        "drupal/views_slideshow": "^4.3",
        "drupal/ds": "^3.1",
        "wikimedia/composer-merge-plugin": "^1.3",
        "drupal/dynamic_entity_reference": "^1.0",
        "drupal/contact_block": "^1.4",
        "drupal/mailchimp": "^1.2",
        "drupal/themable_forms": "^1.0@alpha",
        "drupal/key_value": "^1.0",
        "drupal/twig_tweak": "^1.6",
        "drupal/geolocation": "^1.10",
        "drupal/chosen": "^2.3",
        "drupal/contact_storage_export": "^1.10",
        "drupal/migrate_plus": "^4.0",
        "drupal/migrate_tools": "^4.0",
        "drupal/conditional_fields": "1.x-dev",
        "drupal/recaptcha": "^2.2"
    },
```

**Comment by pfrenssen** [comment]
It looks like `@BeforeScenario` hooks are accessing the contexts before the environment is initialized. Ref https://github.com/jhedstrom/drupalextension/issues/386#issuecomment-311707290

**Comment by balsama** [comment]
Reopening this issue based on a secondary problem (after fixing the first based on pfrenssen's suggestion - thanks!)

@phenaproxima you're right - refactoring [EntitySubContext](https://github.com/balsama/lightning/blob/8.x-2.x/tests/features/bootstrap/entity.behat.inc) to have static methods to avoid [this failure](https://travis-ci.org/balsama/lightning/jobs/248096329#L2740) is ugly. I'm curious as to what you're other ideas were, @phenaproxima.

**Comment by phenaproxima** [comment]
I think we should kill off our gatherContexts() methods and simply use getContext() as needed in our various step definitions.

**Comment by balsama** [comment]
@phenaproxima to be clear, that's already done ([branch](https://github.com/acquia/lightning/compare/8.x-2.x...balsama:behat-version); [tests](https://travis-ci.org/balsama/lightning/builds/248096325)). But there are some [additional failures now that are related to EntitySubContext methods being called statically](https://travis-ci.org/balsama/lightning/builds/248096325).

**Comment by balsama** [comment]
Related: #457

**Comment by alexdesignworks** [comment]
This issue currently blocks installing profile as dependency, because LightningExtension breaks all the other tests. Is there a way to make LightningExtension stop injecting itself into behat config setup outside of lightning?

**Comment by balsama** [comment]
Lightning uses drupal-extension ~3.3.0 now. If this is still an issue, please reopen on D.O.
