### ISSUE TITLE
Managing Lightning configuration requires running entity-updates after site install

### ISSUE THREAD

**Issue by danepowell** [acquia/lightning#387]
The ideal way to manage configuration for a site using Lightning would be something like this:

1. Install site initially using the Lightning profile (or subprofile)
2. Make project-specific modifications to site (adding custom modules, configuration, etc...)
3. Exported site configuration to disk (`drush cex`)
4. On subsequent installations, use the `--config-dir` option with `drush site-install` to import custom configuration added in step 2.

The problem is that currently, after that last step, and after cron has been run, you will have * Mismatched entity and/or field definitions* errors on your Status Report page. You will have to run `drush entity-updates` in order for Drupal to completely sync the configuration.

This is because Lightning creates fields at install time, and Drupal assigns these fields a random UUID. Then when you import the site configuration for those fields (from a previous install), Drupal needs to change the UUID. Unfortunately, this triggers an upstream bug, whereby [Drupal cannot change UUIDs during a config import](https://www.drupal.org/node/2876795), and instead requires cron and entity-updates to be run. This is a really bad developer experience for many reasons, including the fact that entity-updates is a pretty hacky and dangerous command that shouldn't be used on any regular basis.

I'm wondering if there's any way the Lightning team could help get traction on that upstream core issue, to improve the DX for Lightning as well.

Note that this has also been documented in this BLT issue: https://github.com/acquia/blt/issues/1297#issuecomment-300030478

**Comment by tizzo** [comment]
Wouldn't a better workflow be to add that configuration into a sub-profile's config/install directory and strip the GUIDs (as described in the [install profile docs](https://www.drupal.org/docs/8/creating-distributions/how-to-write-a-drupal-8-installation-profile#config)?

**Comment by balsama** [comment]
@danepowell to be clear, on subsequent installs, are you running:

```
drush site-install lightning --config-dir=../path/to/config
```

or

```
drush site-install lightning
drush cim
```

I would think that the latter would throw an exception since the site UUID would be different. Just want to be clear before I start digging into this.

**Comment by balsama** [comment]
@tizzo yeah - that might be part of our recommended workaround ultimately. Thanks.

**Comment by danepowell** [comment]
@balsama fwiw, we use the config-dir argument, but it doesn't really matter. That only sets the site UUID. The problem I'm referencing here is field UUIDs, which aren't really affected by drush's config-dir argument.

**Comment by balsama** [comment]
Great. Thanks for the quick response.

**Comment by balsama** [comment]
What if Lightning added UUIDs to our field storage config definitions? What other problems would that cause?

Note that this wouldn't totally fix the problem because there's at least one field storage provided by core (field.storage.block_content.body.yml) that doesn't have a UUID.

**Comment by danepowell** [comment]
Adding UUIDs to Lightning's default config makes sense to me, I don't see what harm it could do. Let's try it!

**Comment by danepowell** [comment]
I just found this core issue that might help to resolve this in the long run, and also indicates that adding default uuids is a good short term solution: https://www.drupal.org/node/1613424

**Comment by balsama** [comment]
@danepowell I don't fully grok the third requirement in that issue, but either way, I didn't get the feeling that it supports adding default UUIDs, even as a short term solution. This jumps out at me:

> Additionally implementing this means we can remove default UUIDs from the all the default config entities which has been discussed at lengths with @\sun, @\chx and myself thinking that **it is extremely risky to use a UUID for something that is not unique as it will be the same on every *[Lightning]* site installed**.

Is there something else in that issue that I'm missing?

**Comment by danepowell** [comment]
I guess we were focused on different parts :smile: 

> In order to support requirements 1 and 2 we added default UUIDs to all configuration entities. This means that it was possible to sync a standard install to a standard install because all the UUIDs were the same.

**Comment by balsama** [comment]
Hah. Yeah, I read that part too. But, taken as a whole, that issue actually makes me more apprehensive.

Pinging @alexpott.
Can you shed some light on what exactly the "risks" are with every install having the same UUID for a piece of config? Lightning is considering adding UUIDs to its config to avoid the problem of importing config on a fresh install which will have different UUIDs.

**Comment by balsama** [comment]
Was having a conversation w @mike-potter and we weren't 100 sure if this is reproducible with standard. It definitely is. Steps to reproduce:

1. drush site-install standard
2. drush config-export
3. drush site install --config-dir=../config/sync
4. drush cron
5. drush entity-updates

![entity-updates](https://user-images.githubusercontent.com/1536654/28289476-bc50415c-6b10-11e7-8015-21da3a4ded7b.gif)

As noted in the video, installing [Standard has another bug that prevents an install from config from completing](https://www.drupal.org/node/2583113), so you need to delete the shortcut config UUID for it to succeed and reveal _this_ bug.

**Comment by mike-potter** [comment]
Yep, I can confirm I reproduced this in both standard and lightning.  I had been just running "drush config-export" after installing and it seemed to think there weren't any changes, but I hadn't seen the schema changes in the status page or from entity-updates.  I agree that this is an issue and makes a clean config workflow problematic.

I think I agree that just adding fixed UUIDs in Lightning is probably a bad idea.  The idea of having the exact same field uuids on every Lightning site worries me, particularly from a security perspective if there is anything bad that could be done with that knowledge.

I wonder if there is some "post config import" event that fires when it's time to import config where Lightning could do it's config creation?  But that wouldn't help with standard/core.  I need to look at the related issues that have been posted but I can imagine that this is a bigger issue around the whole core uuid system.

**Comment by danepowell** [comment]
I'd be okay with closing this issue in favor of https://www.drupal.org/node/2908097

The `--config-dir` argument doesn't even exist (or at least doesn't work) in Drush 9, and long-term I think it's pretty clear that installing profiles from existing config will be the preferred solution to this.

On a completely unrelated note, I just burned several minutes trying to find that issue, which I knew existed, but I forgot that Lightning has two issues queues :roll_eyes:

**Comment by balsama** [comment]
Related to @danepowell's comment: https://www.drupal.org/node/2921680 "Only allow issues to be filed on D.O"

**Comment by danepowell** [comment]
I've tried to summarize the current state of this issue and possible solutions on d.o, I think we can continue discussion there: https://www.drupal.org/project/lightning/issues/2908097#comment-12344053
