### ISSUE TITLE
First applicable bundle still an issue at time of media creation & 'placement' on custom entities

### ISSUE THREAD

**Issue by amcgowanca** [acquia/lightning#395]
**Original issue:** https://github.com/acquia/lightning/issues/374

### Scenario:

1. We've implemented a custom entity which one of its fields references "Media" via Entity Reference field and uses the Entity Browser -> Media browser form widget.
2. This field references a single media bundle that is not the first one based on alphabetical sorting.
3. Using the "Upload" tab within the media browser, creation of the media entity appears correctly and all $bundles specified as per our last patch/contribution all work correctly. After uploading, the user is prompted with the media entity form.
4. Specifying the media name and clicking the submit to place the media, all appears to function correctly, however, the media entity is not yet actually created and when it is created the incorrect bundle is assigned due to no bundles being specified. The EntityFormProxy's getForm() invokes the MediaHelper's createFromInput() method but does not specify the bundles.

Here is an attached screenshot of where the problem begins to originate (see highlighted item).

![image](https://user-images.githubusercontent.com/316512/27599485-ed9dfb26-5b36-11e7-9f44-26f21197ab9a.png)

This should be a simple fix and we should be able to mimic the code we used in the FileUpload's getForm() when specifying the bundles in the file validation #upload_validators specification but instead within the EntityFormProxy so that the bundles are correctly passed to the MediaHelper's createFromInput().

**Comment by balsama** [comment]
Cleaning up our issue queue. I think everything needed is in the PR and this doesn't need to be migrated. Please open on D.O if it does.
