### ISSUE TITLE
Lightning Core's hook_entity_load implementation causing necessary slowness

### ISSUE THREAD

**Issue by billdennen** [acquia/lightning#403]
We've noticed some slowness after upgrading from Lightning 1 to 2.15. According to New Relic, the slowness is the result of Lightning Core's hook_entity_load.

**Comment by balsama** [comment]
It looks like that code is vestigial and can be removed.

**Comment by balsama** [comment]
Just to make sure we weren't missing something, I manually tested path aliases, including with pathauto and manual overrides, with this hook and without it. I couldn't find any unexpected behavior or difference between when it was and wan not present.

Tests are running here: https://travis-ci.org/balsama/lightning/builds/253637252 If they pass, I'll file a PR.
