### ISSUE TITLE
Error installing Contenta with Lightning for progressive decoupling

### ISSUE THREAD

**Issue by GustavoMarcante** [acquia/lightning#407]
I wish to use Lightning in a progressive decoupled strategy to build a content repository with a Drupal front-end now but ready to have decoupled front-ends in the future. As Reservoir proposes a minimal installation, I evaluated that Contenta would be a good choice to do it. But I can not integrate both.

I tried to install Contenta and them install Lightning as a [module](https://www.drupal.org/project/lightning/releases/8.x-2.16) using the "no core" option, but Drupal did not accept, gave the error "Cannot determine the type of project."

Then I tried `composer require acquia/lightning`. Drupal installed many modules. I did `drush updb`, `drush cr`, `php core/rebuild.php`, F5 in the browser, but even this way Lightning modules are not shown in the list.

I observe that i have `"require": {"acquia/lightning": "^2.1"` in composer.json and also the folder lightning in /web/profiles/contrib and the folder lightning_features (wih core, layout, media, overflow) in web/profiles/contrib/lightning/modules, but the modules are not shown in Contenta in Extend Menu (/admin/modules). Am I missing something?

I also tried the opposite: install Lightning first and then Contenta. After `composer create-project acquia/lightning-project lightning` I run `composer require contentacms/contenta_jsonapi` and it installed some packages. But then I run `composer require webflo/drupal-core-strict` (that seems to me as being the two requirements of Contenta) and I got:
> 
> Your requirements could not be resolved to an installable set of packages.  Problem 1
>    - Conclusion: remove composer/installers v1.3.0
>    - Conclusion: don't install composer/installers v1.3.0
>    - webflo/drupal-core-strict 8.3.0 requires composer/installers v1.2.0 -> satisfiable by composer/installers[v1.2.0].
>    - webflo/drupal-core-strict 8.3.1 requires composer/installers v1.2.0 -> satisfiable by composer/installers[v1.2.0].
>    - webflo/drupal-core-strict 8.3.2 requires composer/installers v1.2.0 -> satisfiable by composer/installers[v1.2.0].
>    - webflo/drupal-core-strict 8.3.3 requires composer/installers v1.2.0 -> satisfiable by composer/installers[v1.2.0].
>    - webflo/drupal-core-strict 8.3.4 requires composer/installers v1.2.0 -> satisfiable by composer/installers[v1.2.0].
>    - webflo/drupal-core-strict 8.3.5 requires composer/installers v1.2.0 -> satisfiable by composer/installers[v1.2.0].
>    - webflo/drupal-core-strict 8.3.x-dev requires composer/installers v1.2.0 -> satisfiable by composer/installers[v1.2.0].
>    - webflo/drupal-core-strict 8.4.x-dev requires composer/installers v1.2.0 -> satisfiable by composer/installers[v1.2.0].
>    - webflo/drupal-core-strict 8.3.0-alpha1 requires composer/installers v1.0.21 -> satisfiable by composer/installers[composer require contentacms/contenta_jsonapiv1.0.21].
>    - webflo/drupal-core-strict 8.3.0-beta1 requires composer/installers v1.0.21 -> satisfiable by composer/installers[v1.0.21].
>    - webflo/drupal-core-strict 8.3.0-rc1 requires composer/installers v1.0.21 -> satisfiable by composer/installers[v1.0.21].
>    - webflo/drupal-core-strict 8.3.0-rc2 requires composer/installers v1.0.21 -> satisfiable by composer/installers[v1.0.21].
>    - don't install composer/installers v1.2.0|don't install composer/installers v1.3.0
>    - don't install composer/installers v1.0.21|don't install composer/installers v1.3.0
>    - Installation request for composer/installers (locked at v1.3.0, required as ^1.0) -> satisfiable by composer/installers[v1.3.0].
>    - Installation request for webflo/drupal-core-strict ^8.3 -> satisfiable by webflo/drupal-core-strict[8.3.0, 8.3.0-alpha1, 8.3.0-beta1, 8.3.0-rc1, 8.3.0-rc2, 8.3.1, 8.3.2, 8.3.3, 8.3.4, 8.3.5, 8.3.x-dev, 8.4.x-dev].Installation failed, reverting ./composer.json to its original content.

If I go on and install Drupal using the browser (http://localhost/dir), i can install the site, translations and Contenta example content, but in the site configuration step (6th step) I got this error:

> The website encountered an unexpected error. Please try again later.
> Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">recipes_magazin</em> have unmet dependencies: <em class="placeholder">core.entity_form_display.node.recipe.default (entity_browser.browser.image_library, entity_browser), field.field.node.article.field_image (media_entity.bundle.image), field.storage.node.field_image (media_entity)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of core/lib/Drupal/Core/Config/UnmetDependenciesException.php).
> 
> Drupal\Core\Config\UnmetDependenciesException::create('recipes_magazin', Array) (Line: 480)
> Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'recipes_magazin') (Line: 132)
> Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'recipes_magazin') (Line: 141)
> Drupal\Core\Extension\ModuleInstaller->install(Array, 1) (Line: 83)
> Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array) (Line: 40)
> contenta_jsonapi_install_configure_form_submit(Array, Object)
> call_user_func_array('contenta_jsonapi_install_configure_form_submit', Array) (Line: 111)
> Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 51)
> Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 585)
> Drupal\Core\Form\FormBuilder->processForm('install_configure_form', Array, Object) (Line: 314)
> Drupal\Core\Form\FormBuilder->buildForm('install_configure_form', Object) (Line: 900)
> install_get_form('Drupal\Core\Installer\Form\SiteConfigureForm', Array) (Line: 590)
> install_run_task(Array, Array) (Line: 546)
> install_run_tasks(Array) (Line: 117)
> install_drupal(Object) (Line: 44)

**What would be the best to do?**

**Comment by GustavoMarcante** [comment]
I observe that I installed Contenta (in first case) and Lightning (in the second) using Composer.

Another point is that maybe this issue is related with:
https://github.com/acquia/reservoir/issues/56

**Comment by balsama** [comment]
Hi There.

Unfortunately, Contenta and Lightning are completely incompatible with each other.

Lightning does have plans to bring in some basic support for decoupled apps, but work on that work is just starting. See https://www.drupal.org/node/2896267 for more info.

**Comment by GustavoMarcante** [comment]
@balsama Hi. Would you explain why are they "completely incompatible"? What kind or incompatibility?
Reservoir and Contenta are working together.
Would not be possible to see joining forces around Lightning and Reservoir and Contenta?

**Comment by balsama** [comment]
From slack:

> as far as I understand, Contenta is a profile. Lightning is also a profile. A Drupal installation has exactly one profile - so they're fundamentally not compatible...

> Now, Lightning does support the concept of being a base profile, but a sub-profile of Lightning would have to be developed specifically to work with Lightning

> And that wasn't the goal of Contenta
