### ISSUE TITLE
Entity browser reordering of files broken in lightning 8.x-2.16

### ISSUE THREAD

**Issue by thom8** [acquia/lightning#413]
working on -- https://simplytest.me/project/entity_browser/8.x-1.0
broken on -- https://simplytest.me/project/lightning/8.x-2.16

Steps to reproduce.

1. Enable `Entity Browser example` module.
2. Goto `/node/add/entity_browser_test`
3. Add at least 2 files to a file field and try to reorder them.

**Comment by twerthmueller** [comment]
Follow the discussion on https://www.drupal.org/node/2901225.

**Comment by balsama** [comment]
Closed in favor of ^^
