### ISSUE TITLE
Move profile dependencies to features

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/lightning#415]
There are some profile dependencies (like comment, tour, shortcut, quickedit, search, contact, etc) that maybe could be moved to a module (lightning_contact_form, lightning_search, lightning_page). This would remove more hard dependencies from the profile and make it easier for users to be more selective on which modules they need based on the features they choose to install.

**Comment by balsama** [comment]
Hey Ron.

"Hard dependencies" is a bit of a misnomer when talking about _profile_ dependencies. Profile dependencies have always been a bit of an exception in that they _can_ be uninstalled. (There are several issues around improving this, including a suggestion to introduce the "suggests" key among others) But, to be clear, Lightning is not enforcing that you keep views_ui (for example) installed.

You can disable it through the UI, via config, or exclude it entirely with a sub-profile.

If they were dependencies of a module, however, they could _not_ be uninstalled without uninstalling the module.

Does that clarify things or are you still suggesting that the "soft" profile dependencies are a problem?

**Comment by rlnorthcutt** [comment]
Thanks! Adam H. pointed this out to me in chat. I know that there is a way for subprofiles to alter some of what Lightning does (like roles, for example). Would that method work?

**Comment by rlnorthcutt** [comment]
Looks like you already have support for that by setting exclude_dependencies in the subprofile's info file. Of course, you already thought of that :D

**Comment by balsama** [comment]
Yeah - sorry if that wasn't clear. Just add something like this to your profile info file:

```
base profile:
  name: lightning
  excluded_dependencies:
    - lightning_contact_form
    - lightning_search
```

The Lightning profile generator will even interactively create one for you:

![sub-profile](https://user-images.githubusercontent.com/1536654/28724450-086101f6-7388-11e7-89fb-c6844eb6d1db.gif)
