### ISSUE TITLE
admin/content view column order is inconsistent with rest of admin UI

### ISSUE THREAD

**Issue by briancwald** [acquia/lightning#429]
The fields added by workflow module in the admin/content view are a great addition to seeing the content at a glance, but the fields get added to the end of the table, which is awkward because it pushes the 'operations' column to the middle. The rest of the admin sections have operations as the last column.

Can the operations weight be set to be last?

![screenshot 2017-08-11 13 33 33](https://user-images.githubusercontent.com/776942/29224861-0e349a30-7e9a-11e7-8fda-22cca02516b8.png)

**Comment by balsama** [comment]
Good call. That should be easy enough. Will put it into the next sprint.

**Comment by phenaproxima** [comment]
Fixed in #436.
