### ISSUE TITLE
Content API + simple_oauth causes issues with page_manager

### ISSUE THREAD

**Issue by sylus** [acquia/lightning#437]
Hi there amazing Lightning team!

I am not sure if this is in your purview as page_manager will soon be removed from your packaging but when I updated to v2.1.7 of lightning I was getting a new error in my Travis CI tests. When excluding content api in my sub-profile I no longer get any errors.

I have traced the issue I think to simple_oauth causing issues with page_managers routing layer.

https://travis-ci.org/drupalwxt/wxt/builds/266570338#L1577

Additionally I do have page-manager patched with: http://drupal.org/node/2736385

**Comment by balsama** [comment]
Migrated to https://www.drupal.org/project/lightning/issues/2924498
