### ISSUE TITLE
Lightning requirements break entity_preview from entity_browser

### ISSUE THREAD

**Issue by grahl** [acquia/lightning#442]
We have a site which uses entity previews from entity_form via entity_browser module version 1.1.0.  This causes an exception on attaching the entity:
```
LogicException: The database connection is not serializable. This probably means you are serializing an object that has an indirect reference to the database connection. Adjust your code so that is not necessary. Alternatively, look at DependencySerializationTrait as a temporary solution. in Drupal\Core\Database\Connection->__sleep() (line 1471 of  /docroot/core/lib/Drupal/Core/Database/Connection.php).
```
I have not yet tracked down where this issue was originally introduced, but it is not the 8.3.7 core update, 8.3.6 was affected as well and is apparently fixed in the dev version.

Since lightning has a fixed requirement on exactly 1.1.0, I was unable to introduce a fake 1.1.1 version or just requiring the dev version.

Please consider loosening this requirement and/or please let me know if there is a better solution to handling such a version override.

**Comment by phenaproxima** [comment]
I have a feeling you may have run into a known issue in core. Take a look at this: https://www.drupal.org/node/2904465

Specifically, adding the patch in https://www.drupal.org/node/2893029 may help. Let me know if it does!

**Comment by grahl** [comment]
Thanks for that tip! I'll try to reproduce this next week.

**Comment by dalibor-matura** [comment]
I can confirm that the patch https://www.drupal.org/files/issues/2893029-full-fix-test-from-3.patch from "StringTranslationTrait consumers cannot be reliably serialized without DependencySerializationTrait" (https://www.drupal.org/node/2893029) seems to be the right thing for the problem.

I will do a final testing soon.

**Comment by grahl** [comment]
Works great, thanks!

**Comment by balsama** [comment]
Looks like this can be closed? Please reopen in our D.O issue queue if something still needs to be addressed.
