### ISSUE TITLE
Generated OAuth keys have incorrect permissions when codebase is built with provided tarball

### ISSUE THREAD

**Issue by balsama** [acquia/lightning#443]
If you use the [tarball provided on the Release page](https://github.com/acquia/lightning/releases/tag/2.1.7) to build your codebase (instead of the Composer [scaffold project](https://github.com/acquia/lightning-project#get-started)) the keys generated during the installation of Lightning API are set to 644 instead of 600 (or 660 which is also acceptable).

**Comment by phenaproxima** [comment]
Fixed in #451.
