### ISSUE TITLE
Suppress "Manage moderation" operation for most entity types

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#447]
Right now, Workbench Moderation will add a "Manage moderation" operation to the drop buttons for any bundle entity (i.e., node types, crop types, media types, etc). This may not be desirable for all entity types, so Lightning Workflow should have a UI allowing administrations to toggle the operation for specific entity types.

**Comment by balsama** [comment]
Migrated to https://www.drupal.org/project/lightning/issues/2924504
