### ISSUE TITLE
Overriding an entry in composer.suggested.json

### ISSUE THREAD

**Issue by aangelinsf** [acquia/lightning#450]
I can't seem to find a way to override the entry for memcache that is located in composer.suggested.json. We are locking down versions so that they don't change underneath us so I'd like to use alpha4 of memcache and not track the dev line for our production site. Here is the entry in composer.suggested.json:

```"drupal/memcache": "2.x-dev"```

I have tried conflict, replace clauses and various other forms. Must be missing something. How can I force composer to use a particular version in my composer.json when it has already been specified?

**Comment by balsama** [comment]
I'm not really sure as this project doesn't use the merge plugin, but the following settings have worked for me on another project:

        "merge-plugin": {
            "merge-extra": true,
            "merge-extra-deep": true,
            "merge-scripts": true,
            "replace": false,
            "ignore-duplicates": true
        }
