### ISSUE TITLE
404 immediately after install

### ISSUE THREAD

**Issue by magick93** [acquia/lightning#453]
Hello

I have just done a fresh install on a docker container (install via web browser - not using drush) and then I am redirected to the site.

But the page now shows 404. I can see from the html source that it is a drupal page. 
![image](https://user-images.githubusercontent.com/2173213/30265356-042e0f72-9730-11e7-8990-c2c6bc55c4b3.png)

For example, the source contains:
`<script type="application/json" data-drupal-selector="drupal-settings-json">{"path":{"baseUrl":"\/",....`

I dont see anything obvious in the logs.

Any ideas what went wrong? 
What is the url to login?

I did a fresh install using your 8.x-2.x branch, and again got this
![image](https://user-images.githubusercontent.com/2173213/30266352-31fdac02-9733-11e7-9e1f-1c9c6c3c6345.png)

Thanks for any help

**Comment by balsama** [comment]
Hi there. I can't think of anything in Lightning that would be causing that. We don't do any redirects during install (or otherwise that I can think of).

What happens when you install via drush? What about standard profile?
