### ISSUE TITLE
Update to 3.x branch of Simple OAuth module

### ISSUE THREAD

**Issue by balsama** [acquia/lightning#456]
2.x is no longer supported. Let's see what changed in the 3.x branch!

**Comment by phenaproxima** [comment]
Nothing that broke our tests, apparently. The update path appears to be cohesive: https://travis-ci.org/phenaproxima/lightning/builds/274679576

However...Simple OAuth 3 has a hard dependency on the Consumers module, which is still in dev. We need that module to be tagged before we can possibly update.

**Comment by balsama** [comment]
Related: #452
