### ISSUE TITLE
Update drush/drush to 9

### ISSUE THREAD

**Issue by naveenvalecha** [acquia/lightning#463]
BLT allowed updating the drush to 9.0.0-beta4 See https://github.com/acquia/blt/issues/1985
https://github.com/acquia/blt/commit/6cdde6988e9811675d0d4565ccaf660fb32775cf

While updating the BLT to latest version, I tried to update the drush as well to the latest version, but it breaks because lightning stick with 8.1.13

**Comment by balsama** [comment]
We actually want to have no opinion at all on which version of drush consumers use. See #459.

**Comment by balsama** [comment]
Lightning no longer has an opinion about which version of Drush consumers use. See #464 f54afb52c802b00208aca5192478d01c68ff6db5
