### ISSUE TITLE
[2.1.8] I have updated to latest version and one of the entity_browser patch is not getting applied

### ISSUE THREAD

**Issue by naveenvalecha** [acquia/lightning#471]
- Updating drupal/entity_browser (1.1.0 => 1.3.0):     The package has modified files:
    M config/schema/entity_browser.schema.yml
    M src/Plugin/Field/FieldWidget/EntityReferenceBrowserWidget.php
    M src/Plugin/Field/FieldWidget/FileBrowserWidget.php
    M tests/src/FunctionalJavascript/EntityBrowserTest.php
    M tests/src/Kernel/Extension/EntityBrowserTest.php
    Discard changes [y,n,v,d,s,?]? y
 Checking out 8.x-1.3
  - Applying patches for drupal/entity_browser
    https://www.drupal.org/files/issues/entity-browser-view-context-2865928-14.patch (2865928 - The View widget should filter based on field settings)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/entity-browser-view-context-2865928-14.patch
    https://www.drupal.org/files/issues/2877751-17.patch (2877751 - Inform users how many items they can add to a field that uses an entity browser)

**Comment by dalibor-matura** [comment]
There is an info in the 2.1.8 Changelog (https://github.com/acquia/lightning/releases/tag/2.1.8)

> Fixed a bug where Entity Browser filters might not work after updating to core 8.3.7. (GitHub #441)

So the patch may not be required anymore. Just guessing. I didn't manage to check it out.

**Comment by naveenvalecha** [comment]
[Lightning composer.json](https://github.com/acquia/lightning/blob/8.x-2.x/composer.json#L118 ) contain **the patch which is not getting applied**. This issue should also be reproducible if someone will do the fresh install of lightning.
`composer create-project acquia/lightning-project MY_PROJECT`

**Comment by balsama** [comment]
Hi @naveenvalecha. Interesting. That patch definitely applies to the 8.x-1.3 version of Entity Browser, which we're pinned to.

Can you try deleting Entity Browser entirely and trying to update again? Or, better yet, if you're using BLT, running `composer nuke` and trying again? It should apply.

**Comment by naveenvalecha** [comment]
Thanks @balsama it worked. It was the composer cache which caused the problem.
