### ISSUE TITLE
Add class to embedded media image

### ISSUE THREAD

**Issue by bryden** [acquia/lightning#472]
I'm trying to add a class to an embedded media image, but I don't see a way to do this in lightning's default settings (see below):

![selection_001](https://user-images.githubusercontent.com/17328452/30710982-3c139162-9ed5-11e7-975f-c2925ac87bc0.png)

Is there a way to do this? Basically I'm just looking to add some styling to the image, and want to target it with a class or an ID or something.

**Comment by balsama** [comment]
This is not something that you can currently do. You could possibly target the classes applied by the image style as a workaround.

I've added the Feature Request tag, but I think this is probably something we are unlikely to support. Generally, we don't want editors adding arbitrary classes.

**Comment by balsama** [comment]
Closing this as part of of our D.O issue migration. Please reopen there if this is still valid.
