### ISSUE TITLE
Applying inherited profile patch causes creation of errant code

### ISSUE THREAD

**Issue by timcosgrove** [acquia/lightning#473]
(Replicated against https://github.com/acquia/lightning/tree/2035e55351a9e5fc111a73ebe25bb40c0c977d27).

https://github.com/acquia/lightning/pull/434 Updated the patch from [Allow profiles to provide a base/parent profile and load them in the correct order](https://www.drupal.org/node/1356276) to the most recent version from comment [#360](https://www.drupal.org/files/issues/1356276-360.patch).

This patch, when applied during `composer install`, creates errant directories `docroot/core/b` and `docroot/core/core` (tree in comment). This only appears to happen when applying the patch via composer-patches. Running `git apply` on the patch does not cause the directories to be created. 

Steps to reproduce:

1. Checkout repository, branch `8.x-2.x`.
2. Run `composer install`.

I've also alerted the D.O. issue the patch was pulled from: https://www.drupal.org/node/1356276?page=1#comment-12277804

I am not sure at this time what causes the issue. I have attached a stripped-down composer.json that demonstrates the issue. [composer.json.txt](https://github.com/acquia/lightning/files/1341865/composer.json.txt)

To be clear, this isn't strictly a Lightning issue, but since Lightning includes the patch in its distribution, it may need to be addressed.

**Comment by timcosgrove** [comment]
```
lightning git:(8.x-2.x) cd docroot/core
➜  core git:(8.x-2.x) tree -d .
.
├── assets
│   └── vendor
│       ├── backbone
<snip>
├── b
│   └── core
│       ├── lib
│       │   └── Drupal
│       │       └── Core
│       │           └── Extension
│       ├── modules
│       │   └── config
│       │       └── src
│       │           └── Tests
│       ├── profiles
│       │   ├── testing_inherited
│       │   │   ├── config
│       │   │   │   └── install
│       │   │   └── tests
│       │   │       └── src
│       │   │           └── Functional
│       │   └── testing_subsubprofile
│       │       └── tests
│       │           └── src
│       │               └── Functional
│       └── tests
│           └── Drupal
│               └── KernelTests
│                   └── Core
│                       └── Extension
├── config
│   ├── install
│   └── schema
├── core
│   ├── lib
│   │   └── Drupal
│   │       └── Core
│   │           └── Extension
│   ├── modules
│   │   └── config
│   │       └── src
│   │           └── Tests
│   ├── profiles
│   │   ├── testing_inherited
│   │   │   ├── config
│   │   │   │   └── install
│   │   │   └── tests
│   │   │       └── src
│   │   │           └── Functional
│   │   └── testing_subsubprofile
│   │       └── tests
│   │           └── src
│   │               └── Functional
│   └── tests
│       └── Drupal
│           └── KernelTests
│               └── Core
│                   └── Extension
├── includes
├── lib
│   └── Drupal
│       ├── Component
│       │   ├── Annotation
<snip>
```

**Comment by timcosgrove** [comment]
Withdrawing this until I better understand and can reproduce in multiple environments. Apologies for the noise!

**Comment by timcosgrove** [comment]
Confirmed that this happens when git 2.14.x is installed. Possibly related: https://github.com/cweagans/composer-patches/issues/148 

Reopening.

**Comment by balsama** [comment]
Interesting - thanks for reporting. Not sure what we can do in this project though (other than not update to git 2.14.0 for now!) Is there anything specific about the patch that causes it?

**Comment by timcosgrove** [comment]
I have not been able to determine that, unfortunately. It is possible that if the patch were regenerated with up-to-date git, it might apply correctly. 

Also independent verification of https://github.com/cweagans/composer-patches/issues/148#issuecomment-332943096 would be helpful, to help get Cameron's attention.

I can switch back and forth locally with brew, but we build our deploy artifacts on Travis, and Travis runs 2.14.1, so our builds will contain this on deploy regardless of what we do locally.

I'd say feel free to close this as it's not a Lightning issue, but again would appreciate attention on https://github.com/cweagans/composer-patches/issues/148. Anyone who builds Lightning with git 2.14.x will see this issue, given that the profile inheritance patch is part of the build.

**Comment by balsama** [comment]
I'm cleaning up our issue queue and migrating everything to D.O. I don't _think_ this issue needs to be migrated since it's not actionable in this repository. Please reopen on D.O if I've missed something.
