### ISSUE TITLE
Unable to fresh install Lightning 2.18

### ISSUE THREAD

**Issue by ivrh** [acquia/lightning#477]
Trying to do a fresh install of Acquia Lightning using the latest release 2.18 (Releases tab in GitHub, downloading the tarball). 
Also tried composer install using the `lightning-project` repo in GitHub.

Every time using new environment, to avoid carrying the previous configuration over.

Both installation methods result in the same error (either web-based installation or composer). The web-based installation allows me to enter database credentials and fail after that, resulting in a partial database.
The composer installation also populates tables but the tables list same as in web-installer case:

`Error
The website encountered an unexpected error. Please try again later.
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "list" plugin does not exist. in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 52 of core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).
Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition(Array, 'list', 1) (Line: 25)
Drupal\Core\Plugin\DefaultPluginManager->getDefinition('list') (Line: 78)
Drupal\Core\TypedData\TypedDataManager->createInstance('list', Array) (Line: 103)
Drupal\Core\TypedData\TypedDataManager->create(Object, NULL, 'langcode', Object) (Line: 187)
Drupal\Core\TypedData\TypedDataManager->getPropertyInstance(Object, 'langcode', NULL) (Line: 74)
Drupal\Core\Field\FieldTypePluginManager->createFieldItemList(Object, 'langcode', NULL) (Line: 526)
Drupal\Core\Entity\ContentEntityBase->getTranslatedField('langcode', 'x-default') (Line: 490)
Drupal\Core\Entity\ContentEntityBase->get('langcode') (Line: 666)
Drupal\Core\Entity\ContentEntityBase->setDefaultLangcode() (Line: 222)
Drupal\Core\Entity\ContentEntityBase->__construct(Array, 'user', ) (Line: 87)
Drupal\Core\Entity\ContentEntityStorageBase->doCreate(Array) (Line: 184)
Drupal\Core\Entity\EntityStorageBase->create(Array) (Line: 71)
user_install()
call_user_func_array('user_install', Array) (Line: 391)
Drupal\Core\Extension\ModuleHandler->invoke('user', 'install') (Line: 287)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1078)
install_base_system(Array) (Line: 668)
install_run_task(Array, Array) (Line: 546)
install_run_tasks(Array) (Line: 117)
install_drupal(Object) (Line: 44)`

Any ideas?

**Comment by balsama** [comment]
Related: #455 ?

**Comment by ivrh** [comment]
Using BeetboxVM and confirming the problem is consistent/easily reproducible.

I have created a support request here: https://github.com/beetboxvm/beetbox/issues/454

Confirming the installation works in non-vagrant VM environment just fine.

**Comment by xmacinfo** [comment]
I can reproduce this issue using the following 3 install profiles:
  [0] minimal
  [1] standard
  [2] lightning

We are experiencing the issue with BLT and Vagrant.

**Comment by balsama** [comment]
I'm migrating relevant issues to D.O and this sounds like beetbox issue. Reopen on D.O if we can help. Thanks.
