### ISSUE TITLE
Content Types > View Json - friendly url

### ISSUE THREAD

**Issue by magick93** [acquia/lightning#484]
Hello

Is it possible to have a url for the Content Type > View Json as a friendly url, that is, a url that doesnt use an id.

The use story is, based on the json, we can generate client code. And if we have consistent, logically named, url, for fetching the json, we can automated a code generation pipeline.

Thanks

**Comment by balsama** [comment]
Hi. You could give existing Content Types aliases at /admin/config/search/path. Would that work? Or are you trying to automate the process when a new content type is created?

**Comment by magick93** [comment]
Yes, exactly. We are trying to automate this.

We typically will design a content type, export it using Features, version control the exported entity, and import it on another installation. Its all very automated.

**Comment by balsama** [comment]
Hmmm. You could probably do something with hook_entity_insert() that would generate the alias when you create the entity type. Lightning API already has and entity_insert hook which could possibly be extended to generate a predictable alias.

**Comment by balsama** [comment]
Migrated to https://www.drupal.org/project/lightning/issues/2924503
