### ISSUE TITLE
Ignore failing Behat test scenarios

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#487]
This is just a reference issue open for posterity, so we remember what happened.

Over in the core-media branch (slated to be merged into 8.x-2.x in the not-too-distant future), we had to disable parts of the tests in media/bulk_upload.feature and media/browser_upload.feature. For some reason, Travis CI invariably fails, with absolutely no debugging information, when you try to upload anything that isn't an image. We spent two days trying to debug this, and finally reached the end of our collective tether. So, for now at least, we have commented out the offending parts of those tests. They pass locally, every time, with flying colors. As best we can tell, something is broken on Travis CI's end, but since it's so opaque, we cannot tell what that could be.

**Comment by balsama** [comment]
Migrated to https://www.drupal.org/project/lightning/issues/2924510
