### ISSUE TITLE
Panelizer: 500 Error when trying to Save 'Manage Content'

### ISSUE THREAD

**Issue by CoolBlueNerd** [acquia/lightning#508]
We are using the Lightning Distribution, using the latest version (2.2.2), Panels & Panelizer that is bundled with the Lightning Distribution, and when we are trying to save after doing 'Manage Content' (even simply placing a Menu Block or a custom basic block) the following errors are reported within the 'Recent log messages':

`Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 133 of /var/www/drupal.dev/docroot/core/lib/Drupal/Core/Entity/EntityTypeManager.php).`

Here's the URL that is passed via AJAX:

`http://drupal.dev/admin/panels_ipe/variant/panelizer_default/*node:1:full:default/layouts/layout_twocol_bricks`

**Comment by balsama** [comment]
Migrated to https://www.drupal.org/project/lightning/issues/2924511
