### ISSUE TITLE
Split OAuth functionality from Content API

### ISSUE THREAD

**Issue by danepowell** [acquia/lightning#511]
The OAuth module is finicky to set up, especially on ACE, and tends to cause trouble for folks who aren't aware of the extra work required: https://github.com/acquia/lightning/issues/445, https://github.com/jenter/decoupled-drupal/issues/16

As far as I know, OAuth isn't required for many sites. For instance, if you have a Drupal backend that serves entirely public / anonymous-accessible content. Thus, it would be nice to split everything requiring OAuth into a separate dependency that could be disabled if not needed.

Alternatively, I would be happy if we could tweak Simple OAuth to fail more gracefully when not configured with keys, correct permissions, etc...

**Comment by mattgrill** [comment]
@balsama If all your clients are connecting without any authentication then how do you revoke any access? From my perspective, using oauth keys has two benefits, A) controlling access to specific resources, B) being able to revoke a clients access if something bad happens.

**Comment by balsama** [comment]
Makes sense. It sounds like, OOTB, we should think about disallowing access to any resource (published or not) without authentication.

That doesn't necessarily mean that the OAuth functionality *shouldn't* be split out into a submodule still as @danepowell is requesting.

**Comment by danepowell** [comment]
Ah, silly me... I didn't realize we could simply opt to not create the keys, since I think they were mandatory back when we set up the project where we are testing this. That might be a viable solution for us, and would be the functional equivalent of "not using OAuth". Let me test and report back.
