### ISSUE TITLE
Edit image cropping from image field on node

### ISSUE THREAD

**Issue by greenacorn-michael** [acquia/lightning#512]
After adding an Image field to the Basic page content type there is no way to edit the cropping of the image from the node edit form. You can set the crop when uploading the image, or via /media/%/edit, but not when editing the existing node.

Is there a way to achieve this out of the box? I have found that installing File Entity (8.x-2.0-beta4) adds the Edit button directly on the node form with no additional configuration required. Is this the suggested solution? Are there discussions about including File Entity in the distribution?

**Comment by balsama** [comment]
Migrated to https://www.drupal.org/project/lightning/issues/2924505
