### ISSUE TITLE
Support audio media assets

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#62]
There's a media_entity_audio module. Lightning Media should support it with the same degree of awesomeness as it supports images, video, Twitter, and Instagram.

**Comment by balsama** [comment]
We had a specific request to support spotify playlists with media. Would be nice if that's something that media_entity_audio could support.

**Comment by phenaproxima** [comment]
Out of the box, I would suggest that we only support SoundCloud audio. It shouldn't (hopefully) be too hard to graft this on to our existing media system.

**Comment by phenaproxima** [comment]
SoundCloud support (along with several other third-party media providers) has happened in contrib: https://www.drupal.org/project/lightning_media_soundcloud

It's mentioned in our README, so unless people are really clamoring for SoundCloud support (and I haven't heard anybody do that), I think we can close this issue.
