### ISSUE TITLE
CKEditor does not support inline style attributes

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#88]
It appears to be impossible for users to apply custom CSS to rich text using inline style attributes. This is absolutely something we should support -- it's completely non-disruptive to normal users, but technical users who need to touch up CSS in one place will hugely benefit from this feature.

**Comment by balsama** [comment]
Relevant: https://www.drupal.org/node/205160

**Comment by balsama** [comment]
This just isn't something that people have asked for. We can file a new issue if it comes back up.
