### ISSUE TITLE
Provide a shortcut link to custom block library

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#89]
To get to the custom block library, one must click through Structure > Block Layout > Custom Block Library. This is sub-optimal. It's pretty low-hanging fruit to add a link to the custom blocks, which (at least for now) remain the single best way to get completely custom content into a landing page layout.

**Comment by balsama** [comment]
Is this still true now that https://www.drupal.org/node/2636516 is committed?

**Comment by balsama** [comment]
No longer needed - you can create custom block from within the IPE.
