### ISSUE TITLE
Once you embed an entity in CKEditor, it's nearly impossible to escape from it

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#90]
If you embed an entity in CKEditor when there is no other content in the editor yet, you basically can't click outside the drupal-entity element to add other content. In fact, you have to switch into source mode. It must always be possible to escape the drupal-entity element context with a click.

**Comment by brantwynn** [comment]
I've seen this with D7 too.  @DevinCarlson

**Comment by balsama** [comment]
This was largely improved by entity embed in its alpha release back in april.
