### ISSUE TITLE
The page title block exists outside the context of a landing page

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#91]
If you want to remove the page title block from any landing page, you have to literally go and configure the page title block so it doesn't show up on that page. From an authoring standpoint, this sucks.

I think the most sensible thing to do here is provide an option in our landing page wizard which will automatically add the page title block to a new landing page, if the layout has a "header" region; and, if so, disable the core page title block on that landing page.

**Comment by brantwynn** [comment]
You might assume much that people will use consistent names like "header" - they may also have "top" or some other arbitrary name.  Perhaps just toss it into the first region?

**Comment by phenaproxima** [comment]
I propose a hybrid approach -- look first for a "header" or "top" region, and if there isn't one, then throw it into the first region.

**Comment by brantwynn** [comment]
![nod](http://media3.giphy.com/media/tsgNNs93oIbwk/giphy.gif)

**Comment by balsama** [comment]
Pretty sure this isn't relevant anymore, right? @phenaproxima ?
