### ISSUE TITLE
Create a default "button" style for links in CKEditor?

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#92]
Authors may occasionally wish to disguise links as buttons. There should be a style for this, specifically provided by Lightning and imported into our CKEditor configuration. It might be possible to do this using the `appearance(button)` CSS directive.

**Comment by brantwynn** [comment]
This usually comes with your theme, right?  e.g. http://foundation.zurb.com/sites/docs/v/5.5.3/components/buttons.html

**Comment by balsama** [comment]
Agree with @brantwynn here. There are three possible approaches that I see:

1. Provide classes for the most popular front-end frameworks (`button`, `button small` for Zurb, `btn`, `btn-sm` for bootstrap, etc) - but that quickly gets out of hand.
2. Introduce our own CSS, but I have a feeling that will inevitably lead to conflicts and unexpected behavior for themers
3. Provide a configurable button where it defaults to adding something like `.btn` but admins can change the class through an interface somewhere to match the front end theme/framework they are using.

Only option 3 seem viable to me. I'm not opposed to it, but it's probably a fairly low priority - at least for now.

**Comment by balsama** [comment]
This is something that could be done in contrib possibly. Not something people are asking for, likely because it's so theme dependent.
